### ISSUE TITLE
consider moving zipkin-ui assets under /static

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1031]
currently, zipkin-ui's assets are included in the root directory. This has an interesting side-effect of making all contents of the zipkin-web jar fetchable by the static asset handler. For example, you can download classes and other properties in the jar via GET.

If we packaged zipkin-ui's assets under "/static", then only those assets would be served. Also, it has a side-effect of being automatically exported in spring-boot apps.

Alternatively, we could get fancier and make zipkin-ui a WebJar by moving the static assets under a path  "/META-INF/resources/webjars/zipkinui/1.37.0" (or whatever version) http://www.webjars.org/

**Comment by codefromthecrypt** [comment]
cc @abesto @eirslett

**Comment by abesto** [comment]
Can do. Would also simplify the handler logic a bit. Reasoning for the current setup is in https://github.com/openzipkin/zipkin/pull/1024#issuecomment-195077081

I have minimal experience with WebJars, was pretty smooth when I used it. But if we go that way, wouldn't we want to use that for dependency management (instead of `npm`)? How would that work together with webpack?

**Comment by codefromthecrypt** [comment]
I think the two current consumers of this are already using maven
dependencies, and that simplifies the build quite a bit. I'd vote for a jar
with "/static" in it, as a published artifact (at least for now).

I've really no experience with webjars or webpack

**Comment by abesto** [comment]
SGTM. @eirslett, you mentioned this is easy to do with webpack?
