### ISSUE TITLE
High level steps to instrument a Java application and get results on Zipkin UI

### ISSUE THREAD

**Issue by fluidjeel** [openzipkin/zipkin#1084]
Hi,

I have recently setup Zipkin and Zookeper as per the documentation. I have also brave library for Java. 
However, I am struggling to find anywhere what will be the next steps. Is there any documentation or reference that i can follow to instrument a sample application.

If someone who has already Instrumented for Java/Jersey2 can provide the high level steps / sample reference would be of great help. 

Sorry if this is a duplicate, i couldn't find any related open request.

**Comment by eirslett** [comment]
1) You don't need ZooKeeper, unless you want to use Kafka for transporting trace data from applications into Zipkin. (In which case you also need to install Kafka). An easier way is to just skip Kafka, and make Brave send HTTP trace data to zipkin directly.
2) Use zipkin-java instead of zipkin-scala, it's easier, and just 1 application/jar, instead of 3.
3) Import Brave as a Java dependency in your application
4) If you have a web application (servlets etc) add Brave's servlet filter, which will intercept incoming traffic.
5) Add more interceptors for instrumentation, like in http clients and jdbc drivers. (Thare are many ready-to-use implementations in the Brave project)
6) Configure Brave so that it sends traces to Zipkin - either to Kafka (if you use that) or directly with HTTP.
7) Start your application, use it a little bit so it generates traffic, watch trace data end up in the Zipkin UI.

**Comment by fluidjeel** [comment]
@eirslett Thanks for you inputs . Looks like a great starting point for me. I would just leave this request open for couple of days incase I have any follow-up questions.
