### ISSUE TITLE
UI does not display binary annotation value if it contains a JSON string

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#1113]
Our instrumentation emits some binary annotations as JSON strings. When returned from query service, it looks all properly escaped:

```
{ "key": "haproxy.LogMessage",
  "value": "{\"msg\":{\"Tw\":\"0\",\"Tt\":\"8625\",\"Tr\":\"0\",\"Tq\":\"8624\",\"Tc\":\"1\",\"backend\", ....
```

But in the span popup it is displayed like this:

```
haproxy.LogMessage  [object Object]
```

cc @eirslett

**Comment by eirslett** [comment]
Yes, that's a "bug" (or feature, if you want) in jQuery. If it encounters a string that looks a bit like JSON, it will parse it as JSON and end up with an object instead of a string.
The fix would be to force the message to be parsed as a string. I'm not sure exactly where in the UI code it happens.

**Comment by codefromthecrypt** [comment]
reproduced by uploading a test span and looking at trace 1

``` bash
$ curl -s -X POST -H 'Content-Type: application/json' localhost:9411/api/v1/spans -d '[{"traceId":"1","name":"bang","id":"2","timestamp":1234,"duration":100,"binaryAnnotations":[{"key":"json","value":"{\"msg\":{\"detail\":\"foo\"}}","endpoint":{"serviceName":"flintstones","ipv4":"127.0.0.1"}}]}]'
$ open http://localhost:9411/traces/1
```

**Comment by codefromthecrypt** [comment]
fooling around here: https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_ui/spanPanel.js#L37

**Comment by anandshah05** [comment]
Same issue for normal annotation values, can you please fix it in logs as well

**Comment by codefromthecrypt** [comment]
zipkin doesn't have logs. I presume you mean to say annotations where
someone encoded json as the value.. first check to see if that is valid.
for example one thing that causes this is OpenTracing, but as far as I
recall, "logs" are encoded in annotation as k1=v1,k2=v2 which is
simultaneously easier to read (in one line) and also not json.

**Comment by anandshah05** [comment]
Yes its annotations. We are actually storing the full json request and response message in annotation so that it become easier to co-relate.

We could use tags, but tag has it own overhead of indexing at database layer (like cassandra, elastic search)

I have added same fix in annotations, can you please verify and merge
