### ISSUE TITLE
Capturing the tracing data from the PL-SQL Stored procedure.

### ISSUE THREAD

**Issue by prateekvjain** [openzipkin/zipkin#1158]
Hi All,
As part of my project I have the tracing thing extended to the PL-SQL Packages in the database.
Idea is to have the trace id and span id passed as parameter to the pl-sql package, which in turn would have the traces generated in the flat file, 
Can you please help in publishing the generic guideliness as to how the trace data capturing can be done by the database package.

To start with the idea, they would have the below generic function, which would have the below data published to flat file.
createSpan(traceid, parentspanid, generated_span_id, "server received", timestamp, packagename)
closeSpan(traceid, parentspanid, generated_span_id, "server sent", timestamp, packagename)

Now i will have two records in the file
traceid, parentspanid, generated_span_id, "server received", timestamp, packagename
traceid, parentspanid, generated_span_id, "server sent", timestamp, packagename

I need to have this data load in the zipkin, I am trying to understand whats the best way to have it published. I cannot have it published all together.
Can i create a Json format below and call the zipkin UI, which in turn take care of traslation for any DB to which its is configured.

If i have JSON format created, I need to have Server send and server recived published seperately.

{
    "traceId": "beeae08bfaa5c2d3",
    "name": "****_",
    "id": "beeae08bfaa5c2d3",
    "timestamp": 1467222628696000,
    "duration": 65000,
    "annotations": [
      {
        "timestamp": 1467222628696000,
        "value": "sr",
        "endpoint": {
          "serviceName": "**_",
          "ipv4": "****_",
          "port": 10000
        }
      },
      {
        "timestamp": 1467222628761000,
        "value": "ss",
        "endpoint": {
          "serviceName": "**__",
          "ipv4": "_****",
          "port": 10000
        }
      }

**Comment by codefromthecrypt** [comment]
This is a bit large a topic to address in this repo, and wouldn't likely affect any code inside of it. Open-ended questions are better for gitter or zipkin-user, probably best gitter.

https://gitter.im/openzipkin/zipkin
https://groups.google.com/forum/#!forum/zipkin-user

Since what you are trying to do has multiple aspects, you might want to create a github repo on your research project and add an issues to it there. For example, how to accept trace identifiers.. how to report json (or otherwise) back to zipkin. Dividing concerns can help make helping more approachable, as people often don't have time to address several topics at the same time.

What would also make things more approachable is not doing this in Oracle. For example, see if you can create a scenario similar enough in something like mysql or postgresql. Then, port your approach to Oracle.

Back to specifics, I don't think there's any existing SQL database accepting traces propagated from a zipkin-instrumented caller. There is one for cassandra https://github.com/thelastpickle/cassandra-zipkin-tracing

There may be some topics on our documentation site that need added to or elaborated. Here are some notes that may be interesting to you:

https://github.com/openzipkin/openzipkin.github.io/issues/31
https://github.com/openzipkin/openzipkin.github.io/issues/11

feel free to ask more questions here https://gitter.im/openzipkin/zipkin and good luck
