### ISSUE TITLE
View Zipkin Data in Kibana as Event-based Data

### ISSUE THREAD

**Issue by dan-tr** [openzipkin/zipkin#1209]
Currently Zipkin stores the `timestamp` field in Elastsearch as a long value. It does so to preserve the microsecond precision of the timestamp value.

However as a side effect, `timestamp` cannot be indexed as a date/time field and cannot be used as a time field when creating an index view in Kibana.

I'm not sure how to fix this issue in such away as to preserve the microsecond precision and allow for date/time indexing. One idea was to create a new field (`timestamp_millis`?) that would contain just the milliseconds from the `timestamp` field.

**Comment by codefromthecrypt** [comment]
looks like there used to be a convention of `_timestamp`, and now it is `date` https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html

We'd need some function to parse this by truncating Span.timestamp to millis (`timestamp/1000`)

**Comment by codefromthecrypt** [comment]
to clarify things..

We have an index for the zipkin span json, called `zipkin-2016-08-14`. Span documents have a nullable timestamp field, but it is in epoch microseconds, not milliseconds. Basically, it is stored as a long.
Ex. 

``` json
{
  "traceId": "3b47c02255029f91",
  "name": "client-calls-server-via-post",
  "id": "3b47c02255029f91",
  "timestamp": 1455242412402125,
  "duration": 9441,
  "annotations": [],
  "binaryAnnotations": [
    {
      "key": "jaegerClient",
      "value": "Python-0.7.9"
    },
    {
      "key": "lc",
      "value": "client",
      "endpoint": {
        "serviceName": "client",
        "ipv4": "127.0.0.1"
      }
    }
  ]
}
```

We want to index on span.timestamp/1000, via a date attribute or otherwise that Kibana can read, but that isn't stored back into the original document json (ideally). In the above example, where .timestamp=1455242412402125 (epoch micros), the one for kibana would be 1455242412402 (epoch millis).

Here's our [index template](https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/resources/zipkin/storage/elasticsearch/zipkin_template.json). Can someone help us figure out what to do?

**Comment by lukeotterblad** [comment]
You're basically stuck making another field as you can either use their defined formats (of which epoch_millis is one) or define a custom format, which you can do via ...

http://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormat.html

But this effectively uses code similar to below (this example is in groovy):

```
@Grab( 'joda-time:joda-time:2.1' )
import org.joda.time.*
import org.joda.time.format.*

String a = "1455242412402125"

DateTimeFormatter dtf = DateTimeFormat.forPattern( "<insert-your-pattern-here>" ); //<-- There's no pattern you can define to parse the microsecond representation as a string

def timestamp = dtf.parseDateTime( a )

println timestamp 
```

You also cant add any kind of processing layer on the timestamp field (similar to an analyzer for text) such that you could have elasticsearch process your times (prior to indexing) to millis as analyzers are only for string fields. So, it seems like it's either make another field timestamp_millis as originally suggested and index that as a date or write a very nice feature request for adding epoch_micros to the definable date mapping formats. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

**Comment by codefromthecrypt** [comment]
@lukeotterblad thanks for the explanation

**Comment by codefromthecrypt** [comment]
work in progress https://github.com/openzipkin/zipkin/pull/1238
