### ISSUE TITLE
Find all traces where x <= number_of_spans <= y

### ISSUE THREAD

**Issue by mathuo** [openzipkin/zipkin#1215]
Just would be a nice feature - and useful for debugging services i.e. traces with only 1 span may have been lost in the service somewhere.

**Comment by codefromthecrypt** [comment]
In the case you ran into this, did the span look complete? just missing its
children?

**Comment by mathuo** [comment]
We have cases where children are missing, think they may be our fault though. Also get odd cases where the UI displays the spans all as the lightest blue color rather than progressively darker colors as we nest into spans. Do you know the case that causes this UI behavior since the structure still appears, all be it a few spans are missing but the coloring is odd.

**Comment by jorgheymans** [comment]
Closing mostly because
- number of spans is rarely a metric for observability, in this case indeed it seems to have been needed to troubleshoot buggy instrumentation
- this has not been requested by anyone else in the last four years

Also this: 

> We have cases where children are missing, think they may be our fault though. Also get odd cases where the UI displays the spans all as the lightest blue color rather than progressively darker colors as we nest into spans. Do you know the case that causes this UI behavior since the structure still appears, all be it a few spans are missing but the coloring is odd.

This should be checked against Lens, our new UI. I have a feeling that most of these issues were due to faulty instrumentation though. Something like https://github.com/openzipkin/zipkin/issues/1484 where we would be able to highlight in the UI common problems with span data would have probably helped here.
