### ISSUE TITLE
Fix flakey zookeeper test

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1285]
Seems to fail consistently on circleci

```
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 30.419 sec <<< FAILURE!
skipsMalformedData(zipkin.collector.zookeeper.SampleRateUpdaterTest)  Time elapsed: 5.631 sec  <<< FAILURE!
java.lang.AssertionError: 
Expecting:
  <{}>
to contain only:
  <[MapEntry[key="zipkin-server@2.2.2.2:8080", value=200]]>
but could not find the following elements:
  <[MapEntry[key="zipkin-server@2.2.2.2:8080", value=200]]>
```

**Comment by abesto** [comment]
Smells like a race condition to me (never dreamed I'd see `sleepABit` in the public API of a library. And it doesn't even specify how long "a bit" is :D). Since we run the same version and config of ZK on CircleCI as we do on Travis, first guess is less power in the build node. Or maybe I'm missing something, and we know "a bit" must be enough (maybe waits for some locks or something)?

**Comment by codefromthecrypt** [comment]
Hehe nice commentary. I suppose sleepABit is a chummier alternative to 5
tries, except in this case it probably does flake more.

**Comment by codefromthecrypt** [comment]
this is a bit of a hammer, but seems to work (until it doesn't)

https://github.com/openzipkin/zipkin/pull/1340/commits/101fa042b505d1efb089b6ce85ad292839bf3d8d
