### ISSUE TITLE
Allow zipkin-ui to run behind a path

### ISSUE THREAD

**Issue by FrontierPsychiatrist** [openzipkin/zipkin#1319]
Because all paths in zipkin-ui are absolute (e.g. /app-$id.min.js, /config.json) it is not possible to run the app behind a different path than /, even when using a `<base href="$PATH"/>` tag.

It would be really nice if that could be changed to embedd the Zipkin UI in another application (e.g. a bigger monitoring app).

I am also willing to contribute the needed changes if wanted.

**Comment by MHarris021** [comment]
+1, change the paths to be relative to the generated index.html please

Found out that specifying the output.publicPath = "/" in webpack.config.js creates the absolute href links in the generated index.html. If this were made to be "" instead then it should be relative, the only other change I can see that would then need to be made is the ajax request in config.js file. Making the request be "./config.json" instead of "/config.json" or possibly configurable should resolve this Feature Request.

**Comment by knikitin** [comment]
I added the prefix for urls in UI, for using zipkin UI, when it located after the proxy. [fork](https://github.com/knikitin/zipkin/commit/6330e767167669e35ad38e3fd7adffab00100d15)

**Comment by codefromthecrypt** [comment]
dupe of #1229
