### ISSUE TITLE
SQS collector auto configuration

### ISSUE THREAD

**Issue by llinder** [openzipkin/zipkin#1334]
It would be nice to include auto configuration for https://github.com/openzipkin/zipkin-aws/tree/master/collector-sqs so folks don't need to make their own Zipkin builds to take advantage of this.

**Comment by codefromthecrypt** [comment]
I agree (though it should be in the zipkin-aws repo)

For next steps: what to do with such a jar? It needs to be in zipkin's
classpath to auto-configure.

If you look at under the covers, there's optional dependencies in
zipkin-server (for the autoconfiguration we've defined already) So if we
wanted something literally in the exec jar, we'd add it as an optional
dependency.

Otherwise, we or look at alternative ways to do modularity (such as
instructions in projects to add it to the server classpath and/or having
docker download the new modules automatically during image creation).

There will come a point where we'd not want to keep stuffing things into
the exec jar, though I'm not sure if we are there not.

**Comment by llinder** [comment]
Makes sense.  I will move this to the zipkin-aws project. We already make our own Zipkin builds for things like this so not a big deal for us.

I'm not sure there is a one size fits all approach to solve this but instructions for adding it to the classpath is probably the right approach for now.  The trickiest part will probably be managing the zipkin-server.yml file.  Maybe Spring Boot has the ability to overlay files from external sources?  Once thats figured out then maybe we can address the Docker build.
