### ISSUE TITLE
Annotation Query for non-serviceName annotations isn't searchable

### ISSUE THREAD

**Issue by lamdor** [openzipkin/zipkin#1339]
This follows from the discussion on https://github.com/uber/jaeger-client-java/pull/75#discussion_r83072771

Should all annotations require the `endpoint`? It only seems like annotation search is impacted if it isn't given.

I've verified this happens on the elasticsearch and cassandra storage backends, but does not happen with the in-memory storage.

I've got a trace like:

<details>
<summary>

Zipkin Trace</summary>

``` json
[
  {
    "traceId": "83999297bce8b381",
    "id": "83999297bce8b381",
    "name": "root",
    "parentId": "0000000000000000",
    "timestamp": 1476305741232000,
    "duration": 907748,
    "binaryAnnotations": [
      {
        "key": "jaeger.hostname",
        "value": "Luke.local"
      },
      {
        "key": "jaeger.version",
        "value": "Java-0.13.0"
      },
      {
        "key": "lc",
        "value": "learning",
        "endpoint": {
          "serviceName": "learning",
          "ipv4": "255.168.1.106"
        }
      },
      {
        "key": "sampler.param",
        "value": "true"
      },
      {
        "key": "sampler.type",
        "value": "const"
      }
    ]
  },
  {
    "traceId": "83999297bce8b381",
    "id": "6af1c9b9739bfc88",
    "name": "child1",
    "parentId": "83999297bce8b381",
    "timestamp": 1476305741438000,
    "duration": 684537,
    "annotations": [
      {
        "timestamp": 1476305742122000,
        "value": "blah"
      }
    ],
    "binaryAnnotations": [
      {
        "key": "lc",
        "value": "learning",
        "endpoint": {
          "serviceName": "learning",
          "ipv4": "255.168.1.106"
        }
      },
      {
        "key": "test",
        "value": "abc"
      }
    ]
  }
]
```

</details>

If I understand this right, I should be able to query for the `test=abc` and it should return the trace, right? However, the zipkin-ui always sets the `serviceName` parameter, so that gets set to `learning`.

But that doesn't return anything (against ES):

```
~ $ curl http://docker.machine:9411/api/v1/traces\?serviceName\=learning\&annotationQuery\="test=abc"
[]
```

When I do it without the `serviceName` (the ui doesn't allow, but the ES storage does. Cassandra storage gives back an IllegalArgumentException 500), it does return the trace.

When I do it with the `serviceName` and `lc=learning` (which I think should work as the annotation does have the `serviceName`):

```
~ $ curl http://docker.machine:9411/api/v1/traces\?serviceName\=learning\&annotationQuery\="lc=learning"
[[{"traceId":"83999297bce8b381","id":"83999297bce8b381","name":"root","parentId":"0000000000000000","timestamp":1476305741232000,"duration":907748,"binaryAnnotations":[{"key":"jaeger.hostname","value":"Luke.local"},{"key":"jaeger.version","value":"Java-0.13.0"},{"key":"lc","value":"learning","endpoint":{"serviceName":"learning","ipv4":"255.168.1.106"}},{"key":"sampler.param","value":"true"},{"key":"sampler.type","value":"const"}]},{"traceId":"83999297bce8b381","id":"6af1c9b9739bfc88","name":"child1","parentId":"83999297bce8b381","timestamp":1476305741438000,"duration":684537,"annotations":[{"timestamp":1476305742122000,"value":"blah"}],"binaryAnnotations":[{"key":"lc","value":"learning","endpoint":{"serviceName":"learning","ipv4":"255.168.1.106"}},{"key":"test","value":"abc"}]}]]
```

The same is true when searching for regular annotations:

```
~ $ curl http://docker.machine:9411/api/v1/traces\?serviceName\=learning\&annotationQuery\="blah"
[]
```

**Comment by codefromthecrypt** [comment]
yes. annotations and binary annotations are only queryable when they have
an endpoint associated with them.

jaeger should be corrected to backfill endpoints prior to reporting vs only
populating a few.

**Comment by codefromthecrypt** [comment]
So, in our thrift we tried to suggest that endpoint is used for querying along with service name https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L297

While Annotation.host and BinaryAnnotation.host fields are marked "optional", that's only a side effect of the original thrift. The description states that they are used both for query and also dependency links.

My guess is "host" (aka endpoint) was originally marked optional as it was lazy applied right before reporting the span out of process.
https://github.com/twitter/finagle/blob/develop/finagle-zipkin-core/src/main/scala/com/twitter/finagle/zipkin/core/Span.scala#L61

In practice, it is sent with all instrumentation I've seen except Jaeger (which is either an oversight or an intentional incompatibility). That's because there can be multiple hosts in the same span. How do you know which was responsible for that annotation?

So, if you are querying by serviceName, you'll need to report spans with endpoint set. If this is about query by annotation when serviceName a query parameter, I know that isn't fully supported. We'd want a separate issue for that.

This issue seems to show api queries with serviceName present, so the action to take is to fix the incompatibility in jaeger. If the incompatibility is intentional, you could get out by adjusting the ZipkinSender to backfill missing endpoint.host prior to encoding. That way, folks using Zipkin can work regardless of the policy in jaeger's core code.

https://github.com/uber/jaeger-client-java/blob/master/jaeger-zipkin/src/main/java/com/uber/jaeger/senders/zipkin/ZipkinSender.java#L97

**Comment by codefromthecrypt** [comment]
@yurishkuro @vprithvi fyi

the adjustment to jaeger would be similar to finagle.. backfill missing endpoints prior to send. Assuming the incompatibility is intentional, it can be done in the ZipkinSender module, except the ZipkinSender doesn't know what the local endpoint is. You'd need to look it up.

``` java
  public int append(Span span) throws SenderException {
    Endpoint localEndpoint = findLocalEndpoint(span);
    // look for any missing Annotation.host, BinaryAnnotation.host and fill with localEndpoint
    span = backfillEndpoints(span, localEndpoint);
    byte[] next = encoder.encode(span);
    ...
```

**Comment by yurishkuro** [comment]
agreed. As I replied on [jaeger ticket](https://github.com/uber/jaeger-client-java/pull/75), the incompatibility is indeed intentional, as the endpoints are all identical and redundant, so we don't send them nor store them, but we do build the index for all tags/logs.
