### ISSUE TITLE
How to display log content in zipkin UI ?

### ISSUE THREAD

**Issue by FunnyYish** [openzipkin/zipkin#1378]

**Comment by codefromthecrypt** [comment]
It will be hard to answer your question without detail, but generally
speaking the zipkin-ui only shows data in zipkin storage. The only log-like
data in zipkin are annotations (timestamped events in a span). All tracers
support annotations, so that's the closest it gets. if you want to
follow-up please use gitter as open-ended questions aren't great for github
issues https://gitter.im/openzipkin/zipkin
