### ISSUE TITLE
Add the ability to change Elasticsearch index date formatting

### ISSUE THREAD

**Issue by ImFlog** [openzipkin/zipkin#1506]
Hello,
By default, elasticsearch indexes are formatted the following way `
indexname-yyyy.MM.dd`by logstash for example ([doc here](https://www.elastic.co/guide/en/logstash/5.1/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index)).
I recently had a request from a client to match their elasticsearch index pattern (which is the logstash one) and I couldn't because the current elasticsearch one is 'yyyy-MM-dd'. So I was wondering if I could add the support for a `date separator` for the elasticsearch storage ?

PRs are incoming (for the zipkin code, docker image and the dependencies job).
Thanks.

**Comment by codefromthecrypt** [comment]
In all of our storage libraries, reduced configuration buys us advantage when writing other tools which might not share code (or even programming language). It also makes writing instructions less complex, and reduces the surface area of bugs and troubleshooting.

Further, this has been requested only once, which puts it more in the category of "how do I work around this" until it becomes more popular or broadly worth it.

The key here is how to affect the formatter, which is currently an intentionally hidden detail. We have multiple ways to address this, depending on how things are deployed. For example, we could expose the type and allow someone to override it by adding a jar to the classpath. Another way would be to tighten up the format expression prefix such that the whole thing could be overridden (avoiding a "whack-a-mole" problem of introducing a parameter and then later another similar one). Finally, we don't have to expose whatever we do as an env variable, as we could leave it to spring boot defaults which can also be set via properties (essentially as discouraged config).

@ImFlog all the above are just brainstorming, and no way mean I don't want to help. I also appreciate you both describing the use case and raising a potential approach. Before we commit to this (no pun intended), can you describe how you deploy zipkin? This might give us more options on how to achieve the same thing. Do you have any thoughts on which types of ways wouldn't work for you?

cc @openzipkin/elasticsearch

**Comment by codefromthecrypt** [comment]
So just chatted with @ImFlog 

I think the raised pull request is good stuff, I just want someone else to get behind this, too. I'll watch for a nod or lack of nod by tomorrow. If there's at least another thumbsup on this comment by tomorrow, I'll merge #1507 after review

---
The general proposal is to supply the ES_DATE_SEPARATOR (or dateSeparator in java), which would override the separator ex. 2017-01-28 could become 2017.01.28

This wouldn't affect the initial separator. Ex `zipkin-2017-01-28` becomes `zipkin-2017.01.28`. not  `zipkin.2017.01.28`

The impact would be that we have to document this, and implement it in the dependencies job, too. The impact is pretty low for most code, since the only thing that cares about the separator is the date range compressor (only used in the query side when a lot of dates are requested ex. last year).

**Comment by mansu** [comment]
The change sounds good.

**Comment by codefromthecrypt** [comment]
here's the change pending merge #1510
