### ISSUE TITLE
Query unfinished traces/operations

### ISSUE THREAD

**Issue by pavolloffay** [openzipkin/zipkin#1516]
There could be situations when users would like to query unfinished traces/operations:

This could be done that user would add "start" tag/log at the beginning and when the operation is considered as finished add "finished" tag/log(in the same span or children spans). Then it would be possible to query on missing finished tag/log.

**Comment by sambishop** [comment]
I don't believe that this feature would be trivial, but I would certainly find it beneficial.  I use Zipkin with a system where traces are long running, and it would be _very_ nice if Zipkin could be used to investigate problems as they are happening, instead of only after the fact.

**Comment by jorgheymans** [comment]
Thanks for the suggestion, I do agree that it does sound useful - to some extent. But the fact that this has not sparked any discussion or reaction after almost four years indicates that most users are probably ok with not having this feature. In any case, implementing this would not be a small feat as @sambishop hints, as the required modifications to the search syntax need to be supported and implemented for all our storage backends. Since we're a small team, we don't implement new storage features lightly unless there's very high and obvious demand for it. 

Closing, feel free to reopen if you still feel strongly about this, or consider raising a PR to get things going.
