### ISSUE TITLE
Bound in-memory storage

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1528]
Right now, the in-memory storage option is unbounded, which means that it can lead to out-of-memory errors which can kill the server. This has come up in the kubernetes repo and again recently when asked by @kellabyte_twitter

> I could see some cases where historical data isn't required, more just tracing "recently" or "whats going wrong right now"

It is possible to make a storage option which can evict based on last timestamp, separately tracking size of index data from encoded spans. There's some related code in zipkin-reporter-java for making a fixed-size for the pending spans queue. Here, codecs support estimating the encoded size (ex that a span is 298bytes or so). Such code could be reused or at least looked at.

By doing something like this, people could have a cheap single-node zipkin which won't blow up on memory, even if it is persistent and not replicated. The tradeoff is that this sort of code, while fun, is even less straightforward than the existing in-memory code.

**Comment by tajdars** [comment]
+1 for bounded InMemoryStorage.

**Comment by harsharastogi** [comment]
+1

**Comment by joel-airspring** [comment]
This would be useful for us too.  I'd like to take a crack at it.

I think it makes sense to take the approach of letting users either set a maximum number of spans or a maximum number of span bytes (using a rough estimate 500 bytes per span), so
  --max-spans=10000
and
  --max-span-bytes=5mb
would be the same.  Or perhaps since this applies to the in-memory storage only, the options should be --max-inmemory-spans and --max-inmemory-span-bytes. . .something like that.

In the process of familiarizing myself with the code, I've made a few cleanups that I'll submit via separate PRs.  I haven't actually written the code to purge the old spans yet, but I hope to tackle that today.

Does that sound OK?

Joel

**Comment by codefromthecrypt** [comment]
Go for simplest auto-purge based on oldest data. I suspect span or trace id
is likely easier to implement, but happy to review whatever proves easiest.

One knob is ideal because we dont want to start encouraging use of mem
storage by adding too many features to it.

**Comment by joel-airspring** [comment]
OK.  I'll just go with a maximum # spans.

I've got a purge() method added to the InMemorySpanStore class.  This method deletes the oldest traces (and their spans) when invoked.  Do you have an opinion on who should do the invoking?  And how?  I'm don't quite know most most idiomatic in Java.  For example:

1. Perhaps InMemoryStorage should have a worker thread that just invokes it every minute or so (cron-like).  In this case, purge() would be being called from outside InMemorySpanStore.
2. Perhaps InMemorySpanStore should invoke it every time a span or group of spans gets added.  This means that purges would be more frequent and consistent, but the naive implementation would add more time to every accept() call.  I'd also rather avoid the contention of multiple calls to purge() all trying to purge the same traces.  One would win, of course, but why do all the extra work?
3. Or perhaps some other idea you might have?

I'll try implementing some of those and see how it works.

Almost there!

**Comment by codefromthecrypt** [comment]
on purge, I'd steal time from the accept method. not worth making any
machinery imho, as it will still be faster than i/o based span stores.
