### ISSUE TITLE
ZooKeeperCollectorSampler

### ISSUE THREAD

**Issue by yzfshuijing** [openzipkin/zipkin#1558]
I'm reading the code,  in ZooKeeperCollectorSampler.java's  there is a method called storeRateGroup, and the code line is 
int newValue = (int) (1.0 * spanCount.getAndSet(0) * 60 / builder.updateFrequency);
can you explain the means of it?  
thanks

**Comment by yzfshuijing** [comment]
I can not understand what 60 means?

**Comment by codefromthecrypt** [comment]
in the javadoc, you'll see that the "target storage rate in spans/minute"
the updateFrequency is documented as "Frequency in seconds which to update the store and sample rate"

so 60 here is seconds in a minute

**Comment by codefromthecrypt** [comment]
to be more specific, the calculation you copy/pasted is how to get the storage rate in spans/minute, given spans since updateFrequency (defaults to every 30s).

**Comment by yzfshuijing** [comment]
@adriancole thanks so much for you explanation, i'v got it 
and i'v the last question 
int discountedAverage = discountedAverage(measurements, discountRate)
Where there is a specific description of the algorithm called 'discountedAverage' 
it's difficult to understand it

**Comment by codefromthecrypt** [comment]
good question. honestly porting this code taught me a lot.

So discounted average is in play to give preference to certain types of
numbers.

for example, if your rate is 10000 spans/second and then you get an
accidental reading of zero spans/second (because a machine malfunctioned
briefly), if would skew an average quite a bit.

The default used adjusts for this, which you can see in play in the unit
tests. For example, small numbers don't impact the discounted average like
they would a normal average. This helps make the adaptive part less fickle,
as it doesn't change the rate as wildly when things happen such as server
restarts.

@Test public void discountedAverage() {
  assertThat(SampleRateCalculator.discountedAverage(asList(10, 5, 0), 1.0f))
      .isEqualTo(5); // normal average

  assertThat(SampleRateCalculator.discountedAverage(asList(10, 5, 0), 0.09f))
      .isEqualTo(9); // smaller discount rate prefers larger numbers

  assertThat(SampleRateCalculator.discountedAverage(asList(1000, 5, 0), 0.09f))
      .isEqualTo(911);
}

**Comment by yzfshuijing** [comment]
@adriancole 
oh, i got it , it's a good way to solve the problem you mentioned above 
thanks for your help again!

**Comment by yzfshuijing** [comment]
these days i used the way of discountedAverage(), i found it just like forgetting factor
we should make sure the first value be big enough, just you test case you given (1000, 5, 0)
except the first value, the other values have a low influence on the average result
@adriancole
