### ISSUE TITLE
Add debug logging to CorrectForClockSkew

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1619]
We added a lot of useful things to the DependencyLinker, as it helps answer or rule out problems quickly. When poking around a negative timestamp issue with @trtg, seems debug logging in CorrectForClockSkew could do the same (ex notify missing ip address or other cause for not affecting a trace).

cc @fedj

**Comment by trtg** [comment]
the clock skew correction requires that all 4 of cs,sr,ss,cr be set or it kicks out early. I have a service written in python that calls a service written in golang. The first service has all four annotations set because py_zipkin does that by default, apparently. The first span in the second service has only sr and ss set but that means clock skew correction does not run and I'm getting negative or massively offset positive  times for this second(golang) service. Someone suggested that mergebyid in zipkin-server would have combined the client span and the server span, but they do not have the same span-id, so that's not happening either. I'm really beginning to grasp at straws as far getting one service to call a remote service and not have their spans be terribly mis-aligned in time.

**Comment by codefromthecrypt** [comment]
In between now and then you should be able to configure go to use the same
span ID. Iirc it is something like ClienServerSameId or similary named (in
zipkin-go-opentracing)

**Comment by codefromthecrypt** [comment]
started on this in #1663. if you enable debug, you'll see some validation warnings like so:
```
skipping redundant root span: traceId=0000000000000001, rootSpanId=0000000000000001, spanId=ffffffffffffffff
skipping clock skew adjustment due to data errors: traceId=0000000000000001
```

More work to do and pull requests welcome

**Comment by jorgheymans** [comment]
`CorrectForClockSkew` was ported to javascript for Zipkin classic here https://github.com/openzipkin/zipkin/commit/d950bd8dc6ab7cc26da85050b976eefb7789f549 . Any enhancements needed to detect invalid trace data in the view layer should be reported directly against Lens.
