### ISSUE TITLE
Consider using rs.fetchMoreResults() in cassandra3 impl

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1647]
In cassandra3, we do this

```java
  private static <K, T> AsyncFunction<ResultSet, Map<K, T>> readResultsAsMap(final Map<K, T> results,
      Function<Row, Map.Entry<K, T>> rowMapper) {
    return new AsyncFunction<ResultSet, Map<K, T>>() {
      @Override public ListenableFuture<Map<K, T>> apply(ResultSet rs) throws Exception {
        // How far we can go without triggering the blocking fetch:
        int remainingInPage = rs.getAvailableWithoutFetching();
```

from @michaelsembwever 
>Would it not be simpler to call rs.fetchMoreResults() ?
>
>fetchMoreResults() is an async call, and improves the chances that the next page is ready to go by the time this page is exhausted.
>
>Taking this approach is simpler as it removes the concurrency/futures from this code, allowing it to be just the single iteration loop

We should reconsider or comment why fetchMoreResults doesn't work cc @llinder 

https://github.com/openzipkin/zipkin/pull/1564#discussion_r126049273

**Comment by jorgheymans** [comment]
Given that [getAvailableWithoutFetching](https://github.com/openzipkin/zipkin/blob/14de677f4a5e987a4a1953ec5d84d6273db3628e/zipkin-storage/cassandra/src/main/java/zipkin2/storage/cassandra/internal/call/AccumulateAllResults.java#L75) has been in place since then, we can close this suggestion. It has been answered also in the linked PR, therefor closing.
