### ISSUE TITLE
Support self-signed certificates with Elasticsearch

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1683]
@aliostad asked about self-signed certificates with ES. I mentioned if this becomes common practice, we could consider supporting it. Looking at spark, it does seem like common practice, as they even have a configuration item for it.

https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#_ssl

Please upvote if you are interested in this cc @openzipkin/elasticsearch

**Comment by aliostad** [comment]
Hi, thank you!

Problem was that we had a valid cert but the hostname was not matching and there is absolutely no way to sort this out.

I spent hours and days (and I am glad because I learnt so much) on it and imported the cert (by creating my own dockerfile and adding steps to do it) only to find out the error is hostname not verified.

I wish we could have an option to disable hostname verification. [This](https://stackoverflow.com/questions/14619781/java-io-ioexception-hostname-was-not-verified) is what I was getting and I could not find a non-code solution. There was a solution by running -javaagent:blah.jar but seems it replaces spring's agent.

**Comment by aliostad** [comment]
👍 +1

**Comment by rangwea** [comment]
@aliostad so,how do you solve this problem?

**Comment by shakuzen** [comment]
Related to #1833?

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/tree/master/zipkin-server#using-a-custom-key-store-or-trust-store-ssl

**Comment by quangnguyen** [comment]
> I wish we could have an option to disable hostname verification.

I still do not see that there is a option to disable hostname verification. This could be a useful thing.
