### ISSUE TITLE
Can ES 2.3.5 use span v2?

### ISSUE THREAD

**Issue by newguylhl** [openzipkin/zipkin#1842]
What kind of issue is this?

 - [ x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Gitter
       or Stack Overflow. https://gitter.im/openzipkin/zipkin https://stackoverflow.com/questions/tagged/zipkin

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed and stay fixed. If you have a solution in mind, skip raising an issue and open a
       pull request instead.

 - [ ] Feature Request. First, look at existing issues to see if the feature has been requested
       before. If you don't find anything, tell us what problem you’re trying to solve. Often a
       solution already exists! Don’t send pull requests to implement new features without first
       getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by newguylhl** [comment]
Could anyone help me please? I have searched but couldn't find answers. 

my environment
filebeat 5.4.3
es 2.35
zipkin 2.4.0

log in es

```
{
  "_index": "zipkin-2017-12-13",
  "_type": "span",
  "_id": "AWBQBtU_LclY2yufRwdG",
  "_score": null,
  "_source": {
    "@timestamp": "2017-12-13T13:18:09.546Z",
    "beat": {
      "hostname": "my host",
      "name": "my name",
      "version": "5.4.3"
    },
    "duration": 612898,
    "id": "9032b04972e475c5",
    "input_type": "log",
    "kind": "SERVER",
    "localEndpoint": {
      "ipv4": "192.168.1.113",
      "serviceName": "brave-webmvc-example"
    },
    "name": "get",
    "offset": 123116,
    "remoteEndpoint": {
      "ipv4": "127.0.0.1",
      "port": 60149,
      "serviceName": ""
    },
    "source": "my log path",
    "timestamp": 1502101460678880,
    "traceId": "9032b04972e475c5",
    "type": "span"
  },
  "fields": {
    "@timestamp": [
      1513171089546
    ]
  },
  "sort": [
    1513171089546
  ]
}
```

json on zipkin web page

```
[
  {
    "traceId": "9032b04972e475c5",
    "id": "9032b04972e475c5",
    "name": "get",
    "timestamp": 1502101460678880,
    "duration": 612898
  }
]
```

Some keys are missing and I cannot search use this link http://localhost:9411/zipkin/api/v2/trace/9032b04972e475c5. But request api v1 can get json above.

The original log is from [here](https://github.com/openzipkin/zipkin/pull/1684). I just remove tags. 

```
$ curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type: application/json' -d'[{
  "traceId": "9032b04972e475c5",
  "id": "9032b04972e475c5",
  "kind": "SERVER",
  "name": "get",
  "timestamp": 1502101460678880,
  "duration": 612898,
  "localEndpoint": {
    "serviceName": "brave-webmvc-example",
    "ipv4": "192.168.1.113"
  },
  "remoteEndpoint": {
    "serviceName": "",
    "ipv4": "127.0.0.1",
    "port": 60149
  },
  "tags": {
    "error": "500 Internal Server Error",
    "http.path": "/a"
  }
}]'
```

**Comment by codefromthecrypt** [comment]
I am not aware of a version problem with 2.3.5. We run tests on ES 2.4.5

The index pattern seems strange as it doesnt have the zipkin:span prefix..
are you sure recent zipkin wrote that document? Could you be running
something older

-A


On 13 Dec 2017 9:29 pm, "newguylhl" <notifications@github.com> wrote:

Could anyone help me please? I have searched but couldn't find answers.

my environment
filebeat 5.4.3
es 2.35
zipkin 2.4.0

log in es

{
  "_index": "zipkin-2017-12-13",
  "_type": "span",
  "_id": "AWBQBtU_LclY2yufRwdG",
  "_score": null,
  "_source": {
    "@timestamp": "2017-12-13T13:18:09.546Z",
    "beat": {
      "hostname": "my host",
      "name": "my name",
      "version": "5.4.3"
    },
    "duration": 612898,
    "id": "9032b04972e475c5",
    "input_type": "log",
    "kind": "SERVER",
    "localEndpoint": {
      "ipv4": "192.168.1.113",
      "serviceName": "brave-webmvc-example"
    },
    "name": "get",
    "offset": 123116,
    "remoteEndpoint": {
      "ipv4": "127.0.0.1",
      "port": 60149,
      "serviceName": ""
    },
    "source": "my log path",
    "timestamp": 1502101460678880,
    "traceId": "9032b04972e475c5",
    "type": "span"
  },
  "fields": {
    "@timestamp": [
      1513171089546
    ]
  },
  "sort": [
    1513171089546
  ]
}

json on zipkin web page

[
  {
    "traceId": "9032b04972e475c5",
    "id": "9032b04972e475c5",
    "name": "get",
    "timestamp": 1502101460678880,
    "duration": 612898
  }
]

Some keys are missing and I cannot search use this link
http://localhost:9411/zipkin/api/v2/trace/9032b04972e475c5. But request api
v1 can get json above.

The original log is from here
<https://github.com/openzipkin/zipkin/pull/1684>. I just remove tags.

$ curl -X POST -s localhost:9411/api/v2/spans -H'Content-Type:
application/json' -d'[{
  "traceId": "9032b04972e475c5",
  "id": "9032b04972e475c5",
  "kind": "SERVER",
  "name": "get",
  "timestamp": 1502101460678880,
  "duration": 612898,
  "localEndpoint": {
    "serviceName": "brave-webmvc-example",
    "ipv4": "192.168.1.113"
  },
  "remoteEndpoint": {
    "serviceName": "",
    "ipv4": "127.0.0.1",
    "port": 60149
  },
  "tags": {
    "error": "500 Internal Server Error",
    "http.path": "/a"
  }
}]'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openzipkin/zipkin/issues/1842#issuecomment-351391319>,
or mute the thread

**Comment by newguylhl** [comment]
Ah, I see. I just test zipkin prefix for api v1 and zipkin:span for api v2. Both works well. Thanks a lot! Close.
