### ISSUE TITLE
Zipkin, can be nested to the traditional spring web project to use together?

### ISSUE THREAD

**Issue by jidianxiake** [openzipkin/zipkin#1853]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Gitter
       or Stack Overflow. https://gitter.im/openzipkin/zipkin https://stackoverflow.com/questions/tagged/zipkin

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed and stay fixed. If you have a solution in mind, skip raising an issue and open a
       pull request instead.

 - [ ] Feature Request. First, look at existing issues to see if the feature has been requested
       before. If you don't find anything, tell us what problem you’re trying to solve. Often a
       solution already exists! Don’t send pull requests to implement new features without first
       getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by codefromthecrypt** [comment]
yes: https://github.com/openzipkin/brave-webmvc-example is an example

**Comment by jidianxiake** [comment]
Zipkin server nested into my own monitoring application

**Comment by codefromthecrypt** [comment]
It is possible, yes, but unsupported.

**Comment by jidianxiake** [comment]
If I do not put together, I will open a separate server, increasing costs

**Comment by jidianxiake** [comment]
If I do that, I need to change my project into a springboot project

**Comment by codefromthecrypt** [comment]
Zipkin is typically used for distributed applications, meaning more than
one process across one or more hosts. It uses a single listen port, so can
share the same host as other processes. Co-locating in one JVM is only
possible with spring boot, unless you write a even more custom app.

People usually encounter issues when they try to make custom servers which
increases the burden on this project which is why it isnt supported. If you
create a custom server you will need to bear the burden of supporting it.
That support burden may cost you more in salary than the resources to start
a couple hundred megabyte JVM.

Hope this info helps guide your decision and good luck.

**Comment by jidianxiake** [comment]
Thanks a lot, but I still have a question, if I really zipkin-ui embedded in my web project, then loading zipkin js and the page will not have the problem of the context path

**Comment by codefromthecrypt** [comment]
if you want to ask more questions, please use gitter
https://gitter.im/openzipkin/zipkin

Note that the type of questions you are about to ask are the reason why we
don't support this. It costs a lot of time for each person that tries to
make a custom version because of choices and how to get the UI routes
correct etc.
