### ISSUE TITLE
Question about sleuth-zipkin @adriancole 

### ISSUE THREAD

**Issue by pickmonster** [openzipkin/zipkin#1888]
Yesterday. I have asked how to rewrite zipkin storage. Now I have another resolve method. I want rewrite spring-cloud-sleuth-zipkin-stream project. But here haven`t open code. So I just try rewrite it by myself. But I get some exception.
===============warn=============
WARN  o.s.a.r.r.**RejectAndDontRequeueRecoverer** - Retries exhausted for message (Body:'[B@663db818(byte[586])' MessageProperties [headers={spanTraceId=a64a69a60dd4b068, spanId=a64a69a60dd4b068, messageSent=true, spanSampled=0, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans}, timestamp=null, messageId=null, userId=null, receivedUserId=null, appId=null, clusterId=null, type=null, correlationId=null, correlationIdString=null, replyTo=null, contentType=application/x-java-object;type=org.springframework.cloud.sleuth.stream.Spans, contentEncoding=null, contentLength=0, deliveryMode=null, receivedDeliveryMode=PERSISTENT, expiration=null, priority=0, redelivered=false, receivedExchange=sleuth, receivedRoutingKey=sleuth, receivedDelay=null, deliveryTag=1, messageCount=0, consumerTag=amq.ctag-R-g0JKz-e5AuXDt3yoQ1qw, consumerQueue=sleuth.sleuth])
===========exception=============
org.springframework.messaging.MessageDeliveryException: failed to send Message to channel 'null'; nested exception is java.lang.IllegalArgumentException: payload must not be null
===========my code==============
@MessageEndpoint
public class SleuthConsumerListener {
    private static final Logger LOGGER = LoggerFactory.getLogger(SleuthConsumerListener.class);

    @StreamListener("sleuth")
    public void sink(Spans input) {
        System.out.println(input);
//        List converted = ConvertToZipkinSpanList.convert(input);
    }

}
=============yml================
server:
  port: 9990

spring:
  cloud:
    stream:
      defaultBinder: rabbit
      bindings:
        input:
          destination: sleuth
          group: sleuth
#          contentType: application/json
  rabbitmq:
    host: localhost
    post: 5672
    username: guest
    password: guest

**Comment by codefromthecrypt** [comment]
One of the reasons we don't support something is because of the labor involved in supporting it (answering questions, fixing bugs, etc). Unfortunately, this doesn't become less of a problem when someone tries to rewrite something we intentionally dropped. You can feel free to ask questions of exploratory nature on gitter, but please don't open issues. When on gitter, some might help, but in general it is best to stick with supported software.

Here's the gitter for sleuth https://gitter.im/spring-cloud/spring-cloud-sleuth
Here's the gitter for zipkin https://gitter.im/openzipkin/zipkin
