### ISSUE TITLE
Why some spans don't have the parent root and the number of spans is too large?

### ISSUE THREAD

**Issue by CyberDick** [openzipkin/zipkin#1905]
![image](https://user-images.githubusercontent.com/15179117/35788627-6d8259ba-0a71-11e8-945a-0cd708cb9dc8.png)

![image](https://user-images.githubusercontent.com/15179117/35788625-6925dfa4-0a71-11e8-82c9-2270aaecc405.png)

**Comment by codefromthecrypt** [comment]
A lot of services set the root span to have the same span ID as the trace
ID. This helps from generating another random number.

If there are a lot of spans, it could be because many operations are in the
same trace.

Please prefer stack overflow or https://gitter.im/openzipkin/zipkin for
questions as github issues are for changes to the codebase.

This type of concern is a question, not a change, so please contact on
https://gitter.im/openzipkin/zipkin for questions or troubleshooting
