### ISSUE TITLE
Getting 404 errors related to .properties files

### ISSUE THREAD

**Issue by Strandedpirate** [openzipkin/zipkin#1911]
I'm running the latest docker build (2.4.5) and getting 404 errors as well as console errors related to a few `.properties` files. This causes the UI to have nothing in it for ~20 seconds and then finally renders.

Looks like these files don't exist in source control either. What's the fix for this?

nav_en.properties
nav_en_US.properties
traces_en.properties
traces_en_US.properties

![zipkin ui 404](https://user-images.githubusercontent.com/1452996/36018804-b3ac5ef8-0d42-11e8-9d16-a6cc9cfb1645.png)

![zipkin ui console errors](https://user-images.githubusercontent.com/1452996/36018667-38dc0552-0d42-11e8-9c39-0ca417492421.png)

**Comment by codefromthecrypt** [comment]
The i18n library is just looking for refined data right? (Ex american
dialect). 404 is not an error per se, just not finding something better

**Comment by Strandedpirate** [comment]
The UI has nothing in it for ~20 seconds and only renders after the uncaught error in `jquery.il8n.properties` displays.

**Comment by codefromthecrypt** [comment]
maybe look at this related commit? 54f66a72389b854ae6ba734cf9ddd6b9cc1a8cc1 It is possible that what needs to change is upstream in https://github.com/jquery-i18n-properties but maybe it is configurable cc @igorwwwwwwwwwwwwwwwwwwww

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
i believe the slowness in rendering may be due to #1914. it may not be related to the i18n stuff at all.

also, the 404s on language files were already happening in previous versions of the zipkin-ui, this is inherent in how the i18n plugin operates. so as far as i know, this is pre-existing and "expected" behaviour.

the `length` error on the other hand doesn't look good. it looks like it might be due to a missing key in the language file (based on the code here https://github.com/jquery-i18n-properties/jquery-i18n-properties/blob/master/jquery.i18n.properties.js#L150). this is a bit hard to tell without a reproduce case and the ability to dig deeper. though if the error does not cause the UI to be unusable, I don't think it is absolutely critical.

**Comment by codefromthecrypt** [comment]
leaving this open a bit longer as I don't know the strategies available to avoid 404's. Maybe we can help upstream.. possibly by keeping a config file of known properties files? (ex the server can compute this so there's no maintenance)

**Comment by codefromthecrypt** [comment]
we won't address this i18n library in classic #2487 will likely use a different library in lens
