### ISSUE TITLE
Make cassandra write consistency configurable

### ISSUE THREAD

**Issue by drolando** [openzipkin/zipkin#1920]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Gitter
       or Stack Overflow. https://gitter.im/openzipkin/zipkin https://stackoverflow.com/questions/tagged/zipkin

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed and stay fixed. If you have a solution in mind, skip raising an issue and open a
       pull request instead.

 - [x] Feature Request. First, look at existing issues to see if the feature has been requested
       before. If you don't find anything, tell us what problem you’re trying to solve. Often a
       solution already exists! Don’t send pull requests to implement new features without first
       getting our support. Sometimes we leave features out on purpose to keep the project small.

--------

For Zipkin firehose we use a RF of 1 to keep writes and disk requirements to a minimum. The current code uses consistency ONE or LOCAL_ONE, meaning it'll fail to write if we do a rolling restart of the cluster.

We'd like to set it to ANY, so writes will still work and hints should take care of forwarding the write when the node comes back up.

In any case I think making the consistency configurable via env variable like everything else could be something useful to people in general.

cc @michaelsembwever for comments

**Comment by codefromthecrypt** [comment]
Fyi originally schema install was optional because the defaults were not
good for production only tests (ex rf 1 is for test readback). I think in
some other issue there were some people discussing setup better for prod.

If we do start implying the default schema is production grade, then yeah
we can do some poor person's templating like we do in elasticsearch.
However, partial changes get a bit complex to apply so people may still end
up in a position of having their own private copy of schema.. just
mentioning config impact.

Another option is to employ another tool if exists in cassandra ecosystem
for managing partial schema updates etc.

Anyway I am also interested in what are good things, what is low hanging
fruit etc.

**Comment by drolando** [comment]
I'm not using the default schema. I changed the keyspace to use the NetworkTopologyStrategy, but I still want RF=1.

I think I haven't explained myself well, what I want to make configurable is https://github.com/openzipkin/zipkin/blob/f309c19345069eb09604f09858d427bdb1d3e18a/zipkin-storage/zipkin2_cassandra/src/main/java/zipkin2/storage/cassandra/DefaultSessionFactory.java#L126

**Comment by codefromthecrypt** [comment]
Ahh.. is this the only change you need? It would be easier to punch a hole
for this enum than map a configuration object for all c* options or add a
dependency on spring config that likely would break once v4 of the driver
is out.

Also we can better explain why (we have limited config but at least
recently try to explain why something matters.

**Comment by michaelsembwever** [comment]
Hi @drolando,
 i'm hesitant about the request here for a number of reasons.

 - 'ConsistencyLevel.ANY' is strongly frowned upon. And I'm unaware of anyone actually using it, so can't speak to it's popularity and stability in the C* codebase.
 - RF=1 is not recommended. There's a reason the code logs a warning if RF remains at 1.

For what you're trying to achieve it would be smarter (imo) to use the Zipkin collector, or the kafka transport, as the buffering mechanism as you perform a rolling restart. ('ConsistencyLevel.ANY' really can't be recommended for such buffering.)
For example you could turn off the collector while performing the rolling restart (if insisting on RF=1). Maybe the collector fails gracefully (it does have a retry mechanism in place) and handles the rolling restart already?

Anyway, because this is a improvement request to accept a situation that breaks two recommendations i'd be uneasy about agreeing to it.

**Comment by drolando** [comment]
@michaelsembwever my idea was to allow people to configure it to whatever they want, so they could simply set `CASSANDRA_CONSISTENCY=QUORUM` or `CASSANDRA_CONSISTENCY=ANY`.

What level they set then it's not a zipkin concern, all consistency levels come with different guarantees and tradeoffs.

**Comment by codefromthecrypt** [comment]
@drolando because things land in support there probably is at least a little cause to have concern about setting traps. Usually we document settings with advice on how to use them. If the advice is to please don't use this, it certainly would come at odds with this. It is our concern because we don't have paid support crew to unwind things and all knobs are a way to shoot one's self. We do get a lot of questions we aren't directly responsible for.

To your point though.. have you found anything mick said to be helpful? In hindsight do you really want to set this, and under what circumstance would you. Can you help write advice?

If purely experimental in nature (like what if we click XX?), that's fine but maybe not something to bake in a flag for. We support each thing and it does impact the future, limits how we can change drivers etc. Appreciate your insight regardless and happy to assist if folks stepping back can recommend in good faith exposing this.

**Comment by jorgheymans** [comment]
This issue seems to have reached a conclusion to not do this. @drolando feel free to share how you went about tackling this if you think it's still relevant.
