### ISSUE TITLE
Support for zipkin server as a fully executable jar 

### ISSUE THREAD

**Issue by zeagord** [openzipkin/zipkin#1932]
Currently Zipkin server is not a Fully executable jar which makes it not possible to run as a System V  or SystemD or Windows services. 

https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

**Comment by shakuzen** [comment]
As mentioned on Gitter, the part of doing this for the Zipkin JAR everyone uses that is a concern is the warning in the linked documentation, copied below:

> Fully executable jars work by embedding an extra script at the front of the file. Currently, some tools do not accept this format so you may not always be able to use this technique. For example, `jar -xf` may silently fail to extract a jar or war that has been made fully-executable. It is recommended that you only make your jar or war fully executable if you intend to execute it directly, rather than running it with `java -jar` or deploying it to a servlet container.

For instance, I thought the Cloud Foundry Java buildpack did not support these because it tries to unpack the JAR before running it, but it appears that with the latest version of the Java buildpack, it has no problem running these. My memory may have been before support was added.

So maybe it isn't a big issue that things like `jar -xf` won't work?

**Comment by codefromthecrypt** [comment]
>
> So maybe it isn't a big issue that things like jar -xf won't work?
>
Hmm does jar -xf actually not work? Feels like I would have tried and
noticed this in the past. Maybe the docs in boot are overly cautious? At
any rate, this won't be a war file, just a standalone. If jar -xf doesn't
work on JRE 8+ I'd be surprised, but still we could consider anyway

**Comment by codefromthecrypt** [comment]
interestingly I tried. jar -tf works in JDK 1.8+, jar -xf doesn't work
in 1.8, but it does in version 9

spring boot's header is also quite large.. trying with a smaller one
to see if that was why 1.8 doesn't work (for completeness, not because
I feel using jar instead of unzip is a critical feature)

**Comment by codefromthecrypt** [comment]
nope. making the shell header smaller doesn't make jar from 1.8 work.

Personally, I'm very unconcerned by this limitation. We don't use jar
to extract files anyway, and due to support implications 1.8 will
phase out as a concern anyway

https://github.com/openzipkin/docker-zipkin/blob/master/zipkin/Dockerfile#L29

ITOW, unless others feel strongly, I'm in favor of making this executable

**Comment by codefromthecrypt** [comment]
ps in the advice against doing this if doing "java -jar" I currently
don't see impact to this in 1.8 or 9, though it might be possible. We
should check that using the modules (ex kafka10) there's no weird
loading problem

**Comment by zeagord** [comment]
I made the jar executable and tested in PCF Dev. It works fine. 

```
name:              zipkin
requested state:   started
instances:         1/1
usage:             256M x 1 instances
routes:            zipkin.local.pcfdev.io
last uploaded:     Thu 01 Mar 09:41:41 +07 2018
```

If we are good, i can submit a PR.

**Comment by codefromthecrypt** [comment]
@zeagord do it!

**Comment by zeagord** [comment]
#1934 Submitted the PR.

**Comment by codefromthecrypt** [comment]
thx

**Comment by codefromthecrypt** [comment]
ps unzip has a problem on alpine (eventhough it doesn't on osx) caused the builds to fail last few releases https://quay.io/repository/openzipkin/zipkin?tab=builds

**Comment by codefromthecrypt** [comment]
added a temporary hack until @abesto or someone tells me a better way. respinning releases 2.5.1 forward in docker https://github.com/openzipkin/docker-zipkin/commit/72f5b108ff03ce1a851581f2625382edc9671f0a

**Comment by abesto** [comment]
I mean... wow, this is new to me. So technically `zip` is correct, that's not a valid zip archive :D It starts with a shell script. I'd note that `unzip` can extract the archive even on Alpine, but then complains about the archive not being valid. Here's one way to both fail on other errors, and let the build pass:

```
zip --fix zipkin-server.jar --out zipkin-server.zip
unzip zipkin-server.zip
```

Where `zip --fix` strips out the shell script from the beginning, restoring the general assumption that a jar is a zip.

**Comment by codefromthecrypt** [comment]
This is a better solution. Lets go with it. Nice find!
