### ISSUE TITLE
What will happen if collector is unreachable

### ISSUE THREAD

**Issue by xihw** [openzipkin/zipkin#2073]
If collector is down, how will the service handle the failures ?
Will they swallow the exceptions and discard the traces ? Will they retry to connect ?

**Comment by codefromthecrypt** [comment]
Quick answer is that if a collector being down causes a failure in a application request, that implies a bug in the tracer or the tracer design.

That said, this question is open-ended so better asked on gitter. Please chat for more info if this didn't answer. We use issues for changes to the codebase https://gitter.im/openzipkin/zipkin

**Comment by xihw** [comment]
Sure, just wanted to clarify my question again in case we are not in the same page. 
Collector getting down does not necessary mean bug in tracer. We deployed collector as a separate remote service, it can be down on its own, and I'm just wondering how instrumented service would handle the connection error.

**Comment by codefromthecrypt** [comment]
no I mean that if the tracer stops working because of a temporary
interruption in the collector, it would be a bug. If the tracer causes
memory problems due to long term outage, also a bug. I agree that
collectors can go down. Also, though keep in mind that connections like
this are more brittle when using http transport. Kafka decouples collectors
for example.

Anyway feel free to chat with us if you like more info!
