### ISSUE TITLE
UI slow if the aggregation creates too many buckets 

### ISSUE THREAD

**Issue by sre01sh** [openzipkin/zipkin#2139]
the aggregation zipkin servers sent to Elasticsearch as below:
{
	"_source": false,
	"aggs": {
		"name": {
			"terms": {
				"field": "name",
				"size": 2147483647
			}
		}
	},
	"query": {
		"bool": {
			"filter": {
				"bool": {
					"must": [{
						"range": {
							"timestamp_millis": {
								"from": 1531825045984,
								"include_lower": true,
								"include_upper": true,
								"to": 1531911445984
							}
						}
					},
					{
						"term": {
							"localEndpoint.serviceName": "mobileuser-service"
						}
					}]
				}
			}
		}
	}
}

Warning: 299 Elasticsearch-6.3.0-424e937 "This aggregation creates too many buckets (10001) and will throw an error in future versions. You should update the [search.max_buckets] cluster setting or use the [composite] aggregation to paginate all buckets in multiple requests." "Wed, 18 Jul 2018 08:21:04 GMT"

 - [ ] Question.
1. What is this aggregation used for ?
2. How to resolve this issue?

**Comment by codefromthecrypt** [comment]
do you have variables in your span names? Span names should be fixed
cardinality. If you have something like an http route, make sure this is
used instead of paths with variables in it.

https://github.com/openzipkin/brave/tree/master/instrumentation/http#http-route-cardinality
https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto#L108
https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml#L312

**Comment by sre01sh** [comment]
Thanks for the quick response.   We are using Spring Cloud -Dalston RELEASE with sleuth.  By default, it puts variables in the span name.

**Comment by sre01sh** [comment]
I just tested the lastest Spring Cloud and found the cardinality has been fixed in this Finchley RELEASE,  like span name: " get /user/{userId}"
