### ISSUE TITLE
es  improve search performance and add backend sorting

### ISSUE THREAD

**Issue by zwukong** [openzipkin/zipkin#2147]
i used zipkin with es as backend db some months ago,when the data is small,the performance is ok,but our sample rate is 1,and the data becomed very large,the performance got slow too. Another issue is the sorting is executed in the javascript front end, which is not very correct in some circumstances。
I have thought of some ideas and it works fine now,if you guys  are interested in my ideas ,i will submit  a PR 😄.
my ideas are as follows:
instead of using  es aggregation，i only use filter,because i figure out that one http request is one trace ,there are very small conditions that two url have the same traceid,so the result is  ok.now our es cluster  has more than 200G docs  one day,the performance is still ok .And because of the giving up aggregation,adding sorting is very easy.

**Comment by codefromthecrypt** [comment]
hi and thanks! definitely we can consider things though I do not expect us to change the order as it is not only a matter in ES but other storage like Cassandra. we can't change that because when scrolling through a lot of data server side.. it will be unreasonable. you can look at some older issues about sort order. changing the query api is a big process as we have to support all storage type not just elastic search.

on the skipping aggregation if you can get integration tests to pass then give a try. we also don't want to do more work then necessary. thank you very much for your research.

**Comment by zwukong** [comment]
so i will submit a light PR without sorting,since  sorting indeed  needs a lot of modifications
