### ISSUE TITLE
UI display problem in the latest version of zipkin

### ISSUE THREAD

**Issue by glmapper** [openzipkin/zipkin#2183]
Feature:

![image](https://user-images.githubusercontent.com/35319286/44964930-9fa8d600-af65-11e8-8132-5ce092ca238d.png)

SpanPanel's title should wrap when my serviceName and spanName are too long

**Comment by zeagord** [comment]
Relates to https://github.com/openzipkin/zipkin/issues/1906

**Comment by zeagord** [comment]
I verified this in Chrome, Mozilla and Safari. Text is wrapping. Can you provide the below details?

1. Zipkin Version
2. Browser
3. Reproducible text or a full screenshot.

Sometimes the elements occupies the entires screen because of the parent size or some other column. Without knowing it is hard to debug the problem.

**Comment by jorgheymans** [comment]
This issue references zipkin-classic which is no longer maintained. Note that a similar issue #3058  exists in Lens, the new UI
