### ISSUE TITLE
Parallelizing tests?

### ISSUE THREAD

**Issue by caniszczyk** [openzipkin/zipkin#221]
The build and tests takes quite awhile for Zipkin...

Can we speed things up by parallelizing?

http://about.travis-ci.org/blog/2012-11-28-speeding-up-your-tests-by-parallelizing-them/

**Comment by franklinhu** [comment]
I'll try breaking it up into a few suites:
- common, collector, query, web, cassandra
- hadoop
- test (integration)

**Comment by franklinhu** [comment]
Uhh not sure if that's possible with SBT. We could do one for each submodule

**Comment by franklinhu** [comment]
Ignoring the failed test due to a typo I made, it looks like splitting it up into a suite for each module actually slows things down. Likely due to SBT spending an inordinate amount of time pulling in dependencies, I would imagine. Will try this again after we move to Maven.
https://travis-ci.org/twitter/zipkin/builds/4076470

**Comment by caniszczyk** [comment]
sadness, we'll try again

Also, we should ensure when we move to Maven we enable Zinc for faster compilation:
http://blog.typesafe.com/zinc-and-incremental-compilation

In the future, we may also want to just review our whole dependency tree and see if we can refactor to minimize them:
e.g., 'mvn dependency:tree' should tell us quite a bit
