### ISSUE TITLE
replace javascript i18n library

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2239]
The i18n library we use has been abandoned with some quite severe bugs like #2175. It also relies on resource traffic to get translations which has led to questions about the number of 404 responses issued. We should replace the library with something maintained and ideally less chatty.

I don't know what is best, but https://github.com/airbnb/polyglot.js is maintained.

cc @openzipkin/ui

**Comment by tacigar** [comment]
I have found some problems in UI code.

1. In this commit https://github.com/openzipkin/zipkin/commit/fe143c4fe06c13f4db8db2592f64f76a7d519dfe#diff-da43b9567d422fe9e9bd638551b4d918 , the following change is merged.

```
<nav id="navbar" class="navbar...">
```
↓
```
<nav class="navbar">
```

Because of this, `i18nInit` for `#navbar` is no longer called in https://github.com/openzipkin/zipkin/blob/a40ebcb47986ed1efb85a0543a17611d78404eb2/zipkin-ui/js/page/common.js#L12 .
And like the following, `value` will be `undefined`.

<img width="943" alt="2018-11-14 17 55 05" src="https://user-images.githubusercontent.com/19551419/48471107-7abec200-e836-11e8-93ba-ef6fcd29e955.png">

2. You need to define all elements of `data-i18n`. like the following

```
traces.limit = Limit
traces.lookback = Lookback
traces.lookback.1hour = 1 hour
traces.lookback.3hours = 3 hours
traces.lookback.6hours = 6 hours
traces.lookback.12hours = 12 hours
traces.lookback.1day = 1 day
traces.lookback.2days = 2 days
traces.lookback.7days = 7 days
traces.lookback.custom = Custom
traces.annotationQuery = Annotation Query
traces.des = Please select the criteria for your trace lookup.
```

**Comment by tacigar** [comment]
<img width="1457" alt="2018-11-14 18 09 33" src="https://user-images.githubusercontent.com/19551419/48471964-785d6780-e838-11e8-86d9-252ce2800a31.png">

It works well now

**Comment by codefromthecrypt** [comment]
mind doing pull request? I know we have another UI in progress but nice to
fix this as so many complain.

Especially if you want to add japanese text :D

**Comment by tacigar** [comment]
OK!
I'll make PR (and add japanese text) 👍

**Comment by zeagord** [comment]
Nice catch. Thanks.

**Comment by codefromthecrypt** [comment]
we are not fixing this in classic zipkin. lens will likely use a different library in #2487
