### ISSUE TITLE
Support upload trace in Zipkin Lens UI

### ISSUE THREAD

**Issue by zeagord** [openzipkin/zipkin#2350]
In the legacy UI there is a feature to upload traces and visualise it. We should support the same in the Lens UI

**Comment by tacigar** [comment]
To tell the truth, I am wondering whether this function is necessary...
At least I have never used this...
WDYT? @openzipkin/ui

**Comment by shakuzen** [comment]
Here is the original pull request that added it: https://github.com/openzipkin/zipkin/pull/1884

I definitely used it at my previous job and encouraged others to use it. It is one way of getting around the storage period limitation. That is, for a particular interesting trace, you can save it to your local machine or attach it to an issue (e.g. JIRA) so that others can check that trace at any time easily, without having to worry about the original data expiring from the data store. It's a nicer experience than everyone wanting to do this learning how to POST the data to a locally running instance or something.

**Comment by codefromthecrypt** [comment]
I concur with tommy's summary

**Comment by tacigar** [comment]
@shakuzen @adriancole 
Thank you for your opinions!!!
OK, I see.
I'll implement this feature 🙇

**Comment by shakuzen** [comment]
Resolved via #2447
