### ISSUE TITLE
ZipkinMySQLStorageAutoConfiguration - Found 2 instances of bean applicationTaskExecutor

### ISSUE THREAD

**Issue by joelroyer** [openzipkin/zipkin#2353]
When Zipkin server start, I got this error:

`***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method storage in zipkin2.autoconfigure.storage.mysql.ZipkinMySQLStorageAutoConfiguration required a single bean, but 2 were found:
	- applicationTaskExecutor: defined by method 'applicationTaskExecutor' in class path resource [org/springframework/boot/autoconfigure/task/TaskExecutionAutoConfiguration.class]
	- taskScheduler: defined in null

Action:

Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
`

Zipkin Server 2.11.12, with MySQL AutoConfigure
Using Spring Boot 2.1.2.RELEASE / Spring Cloud Greenwich RC2

**Comment by codefromthecrypt** [comment]
we dont support custom servers. are you suggesting our default build has a
bean conflict or are you noticing something when you build a custom server?

**Comment by joelroyer** [comment]
Yes, our Zipkin is embedded in a custom server, based on Spring Boot 2.1.2.RELEASE and Spring Cloud Greenwich RC2.

Previous version used Spring Boot 2.0.7.RELEASE and Spring Cloud Finchley.SR2 and worked well (no conflict).

**Comment by shakuzen** [comment]
As @adriancole mentioned, we don't support custom servers so we won't debug this issue. If you do figure out how to work around whatever the issue is, feel free to post it here so it might help others that face this problem (despite our advice to avoid making a custom Zipkin Server in the first place). The bean definitions mentioned in the log do not appear to be Zipkin-made beans, anyways, so I doubt the issue is in Zipkin code itself.
