### ISSUE TITLE
Why span name is always lowercase ?

### ISSUE THREAD

**Issue by zhufeizzz** [openzipkin/zipkin#2438]
zipkin2.Span.Builder#name

![image](https://user-images.githubusercontent.com/4591255/54069919-2da7a580-4296-11e9-8eb5-3551a55e526f.png)

All span name has forced to lowercase, and it's hard to identify.

I think it's better to add a switch to let the user choose.

**Comment by codefromthecrypt** [comment]
The reason for this is that some backends primary indexes of service/span
are binary (aka no concept of case sensitivity). So this helps to ensure
the user knows up-front that the data will eventually become downcased.
Otherwise, it would happen later so more surprises. Since we do aggregation
on service and span name, it is important to not miss on silly things like
case.

Agreed that this could be reconsidered, as now people are using zipkin
format out to other systems.. We can think about relaxing this, but can't
forget why we did it in the first place.

An implementation likely would not be user selection though as that is
awkward to do inside a struct library (configuration management of a
builder is weird and hard to reach). Likely, it would just be removing the
constraint.

**Comment by codefromthecrypt** [comment]
right now, people usually use lower-hyphen in case format, btw

**Comment by codefromthecrypt** [comment]
since changing this will impact several things, we need buy-in to do that (and time to address the concerns this would create also). For now, I'm closing this issue, but we can re-open it if things change.

**Comment by csabakos** [comment]
Came here to say that I would also like this feature (to not force lowercase names). @adriancole is there any chance we could reopen this and gauge how much interest there is? Thanks

**Comment by codefromthecrypt** [comment]
interest is one thing, interest in doing the work to accomplish it.. that's the limiting factor. no one I know has several months free time with the only gain being case preservation.

All the work to redo schemas of cassandra indexing to somehow support mixed case search, case deduplication in keyspaces etc, and then transition folks with migration plans.. this is a huge order to place on someone.

Remember tag values can be preserved and span names are usually derived from tags. Practical options are sometimes better than moving huge boulders up a hill.

**Comment by codefromthecrypt** [comment]
ps it isn't just cassandra either, elasticsearch is similar. the span name would be greatly effected in terms of size and performance if switched from keyword to case insensitive. also, we'd open the possibility of bad search results coming back, resulting in client-side deduping on the UI.

It is a tall order, and I'd really recommend using tags as that has no change in the model. For example, we have site-specific tag support in the search and UI and the values there can be mixed case. They appear same as name in the UI controls.

**Comment by csabakos** [comment]
Perhaps we could make this configurable with a simple boolean flag so that people who intend to use a backend that already supports case preservation can use it, and the rest of the community can continue to use the auto-lowercasing behavior.

(My actual use case: I'm using Spring Cloud Sleuth + Brave to report traces to LightStep using Zipkin reporting, and would like to preserve the case of span names and operation names for readability. Most names use PascalCase and this is not something that I can easily change organization-wide.)

**Comment by codefromthecrypt** [comment]
@csabakos brave doesn't lowercase anything except when converting to Zipkin model. I've not seen the Lightstep integration, but there's no reason it has to convert to zipkin model which does the lowercasing. Literally the FinishedSpanHandler was made for rendering data differently for non-zipkin destinations. Please chat on gitter if you want more info as I think the topic isn't related to this thread now that you mention the use case. https://gitter.im/openzipkin/zipkin

**Comment by codefromthecrypt** [comment]
as mentioned in chat, the boolean flag would be hard to pass and awkward on
a value type. Also, we'd be making our code intentionally incompliant with
our own spec which has been stable for ages. Finally an issue doesn't need
to be re-opened in order to have people vote for it.

the only reason I am asked specifically is usually people expect me
personally to do the work. I personally won't be doing this work. I can say
that for sure.

Anyone else can do this if they accept the responsibility that comes along
with it. This issue is about the full-scope feature of case insensitive
data, not the special case of reporting, though.

Since the reporting use-case is specific to Brave, which doesn't even
depend on code in this repo! I moved the issue about this here
https://github.com/openzipkin/brave/issues/1077

A smaller scope issue is easier for volunteers to pick up, if lightstep are
unable to implement a FinishedSpanHandler to do this on their own. Hope
this helps!
