### ISSUE TITLE
Regression: No gzip for search results in Armeria server

### ISSUE THREAD

**Issue by timothybasanov** [openzipkin/zipkin#2495]
After moving to Armeria gzip was disabled with no way of enabling it back

* Gzip compression in Armeria has to be enabled explicitly, looks like it's not enabled yet
* JSON is highly compressible, sending 1MB responses over the network is better than 10MB
* Documentation points to `zipkin.yml`, which has documented compression options that are ignored. They seemingly configure Spring server, which is not covered when Armeria is used

Proposed fix:
```java
@Configuration public class SpringConfiguration {
    @Bean @Order(0) ArmeriaServerConfigurator httpResponseGzipCompressionConfigurator() {
        return serverBuilder -> serverBuilder.decorator(
                s -> new HttpEncodingService(s,
                        mt -> mt.belongsTo(MediaType.ANY_APPLICATION_TYPE) || mt.belongsTo(MediaType.ANY_TEXT_TYPE),
                        1024));
    }

}
```
Note: This does not allow one to configure it, we probably want to reuse "compression" parameters in `Zipkin.yml`

_Reproducible on 12.5.8 version_

**Comment by codefromthecrypt** [comment]
@openzipkin/armeria anyone able to honor the spring compression setting in the armeria spring boot integration? seems best place to address the issue vs here.

**Comment by hyangtack** [comment]
`armeria-spring-boot-webflux-autoconfigure` has the feature but `armeria-spring-boot-autoconfigure` doesn't.
https://github.com/line/armeria/blob/master/spring/boot-webflux-autoconfigure/src/main/java/com/linecorp/armeria/spring/web/reactive/ArmeriaReactiveWebServerFactory.java#L220-L251

We need to back port it to `armeria-spring-boot-autoconfigure` like what we did about ssl configuration, or you need to fix the zipkin code with the proposed fix.

**Comment by anuraaga** [comment]
@adriancole How much of spring is supposed to work with zipkin? I don't think Armeria should be reimplementing all of spring since it's reinventing the wheel. If most features of spring should work it's better to use the webflux integration so all features of spring work for free. My understanding when we migrated to pure armeria without using any bridge like tomcat or webflux was that zipkin-server doesn't need to have full support for spring features.

**Comment by codefromthecrypt** [comment]
@anuraaga I think case-by-case and would guess that compression enabled might be one of those cases that is likely to be asked elsewhere even if asked here first. I might be wrong on that.

**Comment by codefromthecrypt** [comment]
FWIW on this I agree it is a regression, but it was our fault for not having a test case. Because frameworks automatically do gzip we didn't put a test to cover it. We do have a number of issues raised about ensuring the POST endpoint accepts gzip, but this was a gap where we didn't explicitly test that the browser would get gzipped api response if asked.

**Comment by codefromthecrypt** [comment]
PS for the last day and a half, I have been working on code to mitigate library conflicts between what we use in zipkin and zipkin-dependencies the spark job. I don't enjoy these sorts of conflicts.. yet I do them *ALL THE TIME*

when we decided to move to armeria it was in good faith that we could enjoy a certain amount of insulation from inflating those responsibilities even further. Please don't imply there's complete arbitrariness in our choice to not inflate our area of responsibility also into webflux in order to use armeria. I really want this topic to be open and shut. it is simply about compression and I doubt anyone would think that this is an edge case.

**Comment by anuraaga** [comment]
I don't think the decision to leave out webflux was arbitrary or even wrong, but just that it's not so clear how far the spring support in zipkin-server goes. So far there's been three spring features that didn't / don't work out of the box with armeria-spring, which is just to integrate spring DI with armeria servers, not to interface with spring itself

- actuator
- security
- compression

Spring is pretty huge, so I imagine more of these features could come up. webflux and Tomcat are the way armeria is able to interface with spring's huge ecosystem of features and it would be impractical to implement everything directly in armeria I think. Implementing compression is very easy, since it's just enabling a decorator based on a flag, so I don't think it's a problem to take care of it with armeria. Security would be much more complex and I would say probably too much? As long as we're clear that we'd treat them all case-by-case, and that zipkin-server does not intend to support the full Spring featureset, then we're on the same page.

**Comment by codefromthecrypt** [comment]
@anuraaga I think we are on the same page and most things came out during the initial work as we had tests for them.

the spring-security thing is something that might be worth doing in general as it was something we documented, but didn't actively support. The integration appears to be wrapping a servlet request handler. I haven't pushed as hard on that one as yeah we didn't actually support it in the past.

To put another way, each thing we support in zipkin adds liability when moving to spring 3, 4 or whatever's next. I also don't want to support more things and to that degree I'm ok apologizing about the spring-security hook thing if that ends up not ever implemented by armeria.

**Comment by codefromthecrypt** [comment]
I'm gonna put a patch together we can remove later. I think this is a big deal to fix.

**Comment by codefromthecrypt** [comment]
@anuraaga eeek I may have lied a little.. here are the settings we explicitly mentioned. `use-forward-headers` is set and I'm not sure we test that.

```yaml
server:
  port: ${QUERY_PORT:9411}
  use-forward-headers: true
  compression:
    enabled: true
    # compresses any response over min-response-size (default is 2KiB)
    # Includes dynamic json content and large static assets from zipkin-ui
    mime-types: application/json,application/javascript,text/css,image/svg
```
