### ISSUE TITLE
Validate running lens under a reverse proxy

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2519]
https://github.com/apache/incubator-zipkin/pull/1946 implemented reverse proxy configuration, where zipkin was mounted alongside other services. This was addressed by an env variable `ZIPKIN_UI_BASEPATH` described below:

> path prefix placed into the tag in the UI HTML; useful when running behind a reverse proxy. Default "/zipkin"

We need to read that variable from /config.json in lens, then ping @wdittmer @abesto to verify later (unless one of them wants to help implement!)

**Comment by jcchavezs** [comment]
Maybe a browser test would be good here? I think we have some expertise in
my company I could borrow.

**Comment by shakuzen** [comment]
> I think we have some expertise in my company I could borrow.

@jcchavezs just checking back to see if you or someone from your company would be able to help resolve this (it's one of the issues blocking switching the default UI to Lens).

**Comment by jorgheymans** [comment]
I tested this with mod_proxy and a local httpd running on 8080

```
ProxyPass "/myzipkin"  "http://localhost:9411/zipkin"
ProxyPassReverse "/myzipkin"  "http://localhost:9411/zipkin"
```

Started zipkin-server using `java -jar target/zipkin-server-2.16.3-SNAPSHOT-exec.jar --zipkin.ui.basepath=/myzipkin`

Then accessing `http://localhost:8080/myzipkin` ends up loading lens correctly but the browser url becomes `http://localhost:8080/zipkin/` which does not seem desired.

**Comment by codefromthecrypt** [comment]
great. Thanks @jorgheymans. this is progress

**Comment by anuraaga** [comment]
I'm looking at this issue. I know in #1946 we added a mechanism for injecting the base path from the server to read in the client. But wondering, does anyone remember if there was any gotcha from just trying to extract the base path from the current `window.location`?

I think a URL that renders zipkin-lens can only look like one of these patterns
- https://fooserver.com/mysite/myzipkin/
- https://fooserver.com/mysite/myzipkin/dependency
- https://fooserver.com/mysite/myzipkin/traces/39048234098234
- https://fooserver.com/mysite/myzipkin/traceViewer

So simple processing of `window.location.href` can find that the base path is `https://fooserver.com/mysite/myzipkin/`

One corner case is if a user enters there own 404 URL like this
- https://fooserver.com/mysite/myzipkin/foobar/

With just parsing of the URL, we would end up treating this as a base path (the URL to the discover page) of `https://fooserver.com/mysite/myzipkin/foobar/`. Ideally, the reverse proxy itself throw the 404 for this, but in case it doesn't, we'd still be able to do it though if we treat a 404 for `BASE_PATH/config.json` as a 404 page. This doesn't seem too high priority to me though since we're already not very good, lens displays a blank confusing page if a request of an unknown path does make it through (e.g., when using the dev server) so any handling of bad URLs would be an improvement regardless of base path handling.

Interpreting the base path would allow users to proxy without even worrying about setting a property. And it simplifies our dev server too by removing the dev-only `API_BASE` environment variable.

Let me know if you have any concerns about such an approach. /cc @abesto

**Comment by jcchavezs** [comment]
I don't think there was any gotcha before, tho we did not use react (it was
not a SPA either) so it is worth to keep an eye on it (are we using
react-router?).

Any thoughts on this @pchiwan? (Resolving basepath from window.location vs
setting one on beforehand)

**Comment by anuraaga** [comment]
Yup lens uses `react-router`. I'm hoping to extract the base path from `window.location` and pass it to `react-router` using the `basename` prop (as well as using it to configure API calls)

**Comment by jcchavezs** [comment]
I see. The reason I asked was because when I googled "Using
window.location" Google autocompleted "with react" and many results are
related to "react-router".
