### ISSUE TITLE
Sort out DEPENDENCIES file for zipkin-lens

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2548]
zipkin-lens is not a java project, so I doubt the maven-rat-plugin can help with it. We need to figure out what other ASF projects with UIs do about this, whether it is automated or manual. Then, we need to add a DEPENDENCIES file somehow before graduation.

This file should include license notes about packaged dependencies such as fontawesome(#2618) and other things minified into our lens distribution jar

**Comment by codefromthecrypt** [comment]
cc @abesto @devinsba reminder about this issue which we haven't solved yet. I don't know if there are any NPM or webpack tools to generate DEPENDENCIES for web UIs, suspect there aren't. I don't know how many javascript UIs there are in apache that actually do this part.. guessing SkyWalking would be one of them cc @wu-sheng

**Comment by abesto** [comment]
Good news: there's an NPM package for everything. Bad news: there are at least three NPM packages for everything. It seems to me that https://www.npmjs.com/package/license-checker is our best bet. Output for `npm install && npm install --only=dev && npm install -g license-checker && license-checker` in `zipkin-lens`: https://gist.github.com/abesto/dc9fe2e27a0ebe6409b5653d67bf8a99

Does that look good enough to just dump into the `DEPENDENCIES` file during the build process? Do we need any more organization? I'd argue it's long enough to be useless, but maybe it's exactly what we need?

Note also that with `--onlyAllow` this tool can also be used to verify we're using only allowed licenses (we'll need to populate the list ourselves, there isn't an ASF preset, but I remember seeing a comprehensive list of licenses the ASF likes, so that shouldn't be a huge issue).

Using `--summary`, here's the list of licenses used in our dependencies: https://gist.github.com/abesto/e2c0a52445c0e5f06169bfe0faefb299

```
├─ MIT: 1067
├─ ISC: 95
├─ BSD-3-Clause: 33
├─ Apache-2.0: 26
├─ BSD-2-Clause: 24
├─ MIT*: 8
├─ BSD*: 7
├─ BSD: 2
├─ CC-BY-4.0: 2
├─ CC0-1.0: 2
├─ (BSD-3-Clause OR GPL-2.0): 1
├─ (MIT OR Apache-2.0): 1
├─ Apache*: 1
├─ AFLv2.1,BSD: 1
├─ WTFPL: 1
├─ MPL-2.0: 1
├─ (CC-BY-4.0 AND OFL-1.1 AND MIT): 1
├─ (MIT AND Zlib): 1
├─ (WTFPL OR MIT): 1
├─ BSD-3-Clause OR MIT: 1
├─ (MIT AND BSD-3-Clause): 1
├─ CC-BY-3.0: 1
└─ Unlicense: 1
```

**Comment by codefromthecrypt** [comment]
Hi, @abesto good find! I think this license checker would be more an alternative to the maven-rat-plugin, in so far as it can help us identify if we are linking to ASL compatible licenses. We should make sure this only applies to non-dev (non test or build) dependencies. For example, I think RAT only applies to compile dependencies.

Separately, we can figure out the format needs of DEPENDENCIES which would note the license term of each of those who pass.

Does this make sense, mentors? @reta @michaelsembwever @WillemJiang @wu-sheng

**Comment by codefromthecrypt** [comment]
I am trying with the "production" flag now.. cc @tacigar @zeagord @jcchavezs as this would apply to any javascript project built with NPM that ends up in apache

```
# of course.. like always rm -rf node_modues :D
$ npm install && npm install --only=dev && npm install -g license-checker && license-checker --production 
```

**Comment by abesto** [comment]
There's also JSON output, so if there are indeed requirements on the format of `DEPENDENCIES`, it should be relatively easy to post-process into that (or even send a PR to the tool so that others can benefit as well, adding something like an `--asf-dependencies` flag ;) )

Ready to code whenever requirements are settled.

**Comment by jcchavezs** [comment]
Good stuff. I could true it out in zipkin JS now and give some feedback.

søn. 2. jun. 2019, 03:09 skrev Adrian Cole <notifications@github.com>:

**Comment by codefromthecrypt** [comment]
I think first goal would be using the plugin to act like RAT and break the
build if a copy-left production dependency is added. So far, I think we are
good.

$ license-checker --production|grep licenses|sort|uniq
│  ├─ licenses: Apache-2.0
│  ├─ licenses: BSD
│  ├─ licenses: BSD*
│  ├─ licenses: BSD-2-Clause
│  ├─ licenses: BSD-3-Clause
│  ├─ licenses: ISC
│  ├─ licenses: MIT
│  ├─ licenses: MIT*
   ├─ licenses: Apache-2.0


On DEPENDENCIES file is formally defined as even required anywhere.
definitely there is a requirement around bundled (vendored) source (eg in
LICENSE) http://www.apache.org/dev/licensing-howto.html

An aside, but our NOTICE files seem to have redundant info as the above
link says it isn't required to include lines about apache licensed
inclusions!

So, at this point, I'm thinking DEPENDENCIES is a nice to have and not an
ASF requirement, else they would have listed it mandatory and described the
format.
I just spent some some looking for it and failed.. definitely there is a
requirement around bundled (vendored) source (eg in LICENSE), but I can't
see anything that says DEPENDENCIES is even a requirement. Maybe it is a
nice to have?

here's some sample output from the maven plugin regardless.. maybe for now
we just redirect the output from license-checker in its own format to
target/classes/META-INF/DEPENDENCIES under phase "generate-resources"?
NOTE: the normal maven thing doesn't check indirect dependencies, though
npm-checker does..

From: 'Google, Inc.' (http://www.google.com)
  - Google Guice - Core Library (https://github.com/google/guice/guice)
com.google.inject:guice:jar:4.2.1
    License: The Apache Software License, Version 2.0  (
http://www.apache.org/licenses/LICENSE-2.0.txt)
From: 'The Apache Software Foundation' (https://www.apache.org/)
  - Apache Commons CLI (http://commons.apache.org/proper/commons-cli/)
commons-cli:commons-cli:jar:1.4
    License: Apache License, Version 2.0  (
https://www.apache.org/licenses/LICENSE-2.0.txt)
From: 'The Eclipse Foundation' (http://www.eclipse.org/)
  - org.eclipse.sisu.inject (
http://www.eclipse.org/sisu/org.eclipse.sisu.inject/)
org.eclipse.sisu:org.eclipse.sisu.inject:eclipse-plugin:0.3.3
    License: Eclipse Public License, Version 1.0  (
http://www.eclipse.org/legal/epl-v10.html)

**Comment by codefromthecrypt** [comment]
I opened this mail thread as even if we do this anyway, we should declassify this as a graduation blocker unless it is.. https://lists.apache.org/thread.html/4edaa84d2425b40f252f0ea0b1dbf7b8ca8299fd6d23de7f9df62d85@%3Cgeneral.incubator.apache.org%3E

**Comment by codefromthecrypt** [comment]
ok, so DEPENDENCIES is a nice-to-have, but breaking build on copyleft is a requirement.

@abesto does that suffice for requirements? :D

**Comment by abesto** [comment]
> NOTE: the normal maven thing doesn't check indirect dependencies, though npm-checker does..

So... I guess the lazy thing is to use `--direct` to behave the same way as Rat. OTOH as long as all our transitive dependencies are A-OK, we can afford to be more strict.

I've worked through licenses of our dependencies and compared to https://apache.org/legal/resolved.html. Things that stand out:

* `CC-BY-3.0` and `CC-BY-4.0`: ASF says "Works under the Creative Commons Attribution (CC-BY) licenses (2.5, 3.0, and 4.0) contain terms related to "Effective Technological Measures", which may come as a surprise to users. Thus their inclusion shall be appropriately labelled and only in binary form."
  * Packages: `@fortawesome/fontawesome-free`, `spdx-exceptions`, `caniuse-lite`
  * My take: I'm not clear on what "appropriately labelled" means. For fontawesome, we're good on "only in binary form". The other two packages contain stuff that doesn't _have_ a binary form (JSON data and HTML/... components), so I guess we're alright?
* `MPL-2.0`: ASF says "Each license in this section requires some degree of reciprocity. This may mean that additional action is warranted in order to minimize the chance that a user of an Apache product will create a derivative work of a differently-licensed portion of an Apache product without being aware of the applicable requirements."
  * Packages: `mdn-data` (https://github.com/mdn/data)
  * My take: the ASF 3rd-party license policy is vague enough to be useless for me here. No idea whether we're in the clear.

Fun one I didn't know about; "Unlicense" is an actual license name , and it explicitly assigns software to the public domain. Nice.

Assuming the above licenses / uses are cleared, this command does the checking for us:

```
license-checker --onlyAllow 'MIT;ISC;BSD-3-Cluase;Apache-2.0;BSD-2-Cluase;MIT*;BSD*;BSD;CC-BY-4.0;CC-1.0;Apache*;CC-BY-3.0;WTFPL;MPL-2.0;CC0-1.0;Unlicense'
```

We might need to tweak it if new dependencies come in with licenses the ASF likes, but are not in the least. It also outputs the full dump of dependencies (so we can also add `--json | our-preprocessor` if we want, etc).

Let me double down on the mentor ping. How do we handle the above licenses / uses? @reta @michaelsembwever @WillemJiang @wu-sheng

**Comment by codefromthecrypt** [comment]
I think you are missing the --production flag. all the prod dependencies
are straightforward when I checked.. ex RAT doesn't check the test tree iiuc

**Comment by codefromthecrypt** [comment]
PS I don't know the nuance of what deps we need besides production. You are
right that our UI doesn't work without fontawesome. maybe there are some
additional labeling we can use to get "production" + "what we use that
isn't in production" :D

**Comment by WillemJiang** [comment]
For the third party dependency of CC License library , I think we may need to bring it up to the legal-discuss@apache.org to see if we can treat the library as binary ( if we don't change the content).

**Comment by codefromthecrypt** [comment]
let's try to clarify what work has to occur and in a priority order. We do have to look into fontawesome, so let's look closely at this. We may not need to go to legal about it.

```
├─ @fortawesome/fontawesome-free@5.4.1
│  ├─ licenses: (CC-BY-4.0 AND OFL-1.1 AND MIT)
│  ├─ repository: https://github.com/FortAwesome/Font-Awesome
│  ├─ publisher: Dave Gandy
│  ├─ email: dave@fontawesome.com
│  ├─ url: http://twitter.com/davegandy
│  ├─ path: /Users/acole/oss/incubator-zipkin/zipkin-lens/node_modules/@fortawesome/fontawesome-free
│  └─ licenseFile: /Users/acole/oss/incubator-zipkin/zipkin-lens/node_modules/@fortawesome/fontawesome-free/LICENSE.txt
```

Here's the entire text of their license file:

```
Font Awesome Free License
-------------------------

Font Awesome Free is free, open source, and GPL friendly. You can use it for
commercial projects, open source projects, or really almost whatever you want.
Full Font Awesome Free license: https://fontawesome.com/license/free.

# Icons: CC BY 4.0 License (https://creativecommons.org/licenses/by/4.0/)
In the Font Awesome Free download, the CC BY 4.0 license applies to all icons
packaged as SVG and JS file types.

# Fonts: SIL OFL 1.1 License (https://scripts.sil.org/OFL)
In the Font Awesome Free download, the SIL OLF license applies to all icons
packaged as web and desktop font files.

# Code: MIT License (https://opensource.org/licenses/MIT)
In the Font Awesome Free download, the MIT license applies to all non-font and
non-icon files.

# Attribution
Attribution is required by MIT, SIL OLF, and CC BY licenses. Downloaded Font
Awesome Free files already contain embedded comments with sufficient
attribution, so you shouldn't need to do anything additional when using these
files normally.

We've kept attribution comments terse, so we ask that you do not actively work
to remove them from files, especially code. They're a great way for folks to
learn about Font Awesome.

# Brand Icons
All brand icons are trademarks of their respective owners. The use of these
trademarks does not indicate endorsement of the trademark holder by Font
Awesome, nor vice versa. **Please do not use brand logos for any purpose except
to represent the company, product, or service to which they refer.**
```

I will look at what we package and see what's up.

**Comment by codefromthecrypt** [comment]
Our source uses the following cc @tacigar @zeagord 

```
$fa-font-path: "~@fortawesome/fontawesome-free/webfonts";
@import '~@fortawesome/fontawesome-free/scss/fontawesome.scss';
@import '~@fortawesome/fontawesome-free/scss/brands.scss';
@import '~@fortawesome/fontawesome-free/scss/solid.scss';
```

In packaging, this results in files of type eot, ttf, svg, woff and woff2

**Comment by WillemJiang** [comment]
For the fonts and icons, as we normally don't change them and it's hard to change, I think it should be fine to treat them as a binary usage. Any thought?

**Comment by michaelsembwever** [comment]
I also used `license-checker` on Cassandra Reaper when we offered to donate it to Cassandra.

> … the format needs of DEPENDENCIES …

no idea :(
but my understanding was that it is just an exercise to ensure copyleft dependencies don't sneak in. (it is very easy to slip in a dependency via a PR without properly double-checking it.)

>  How do we handle the above licenses / uses?

I think the whitelist approach to the `license-checker` is a good approach. It is only going to break when a new dependency is added and that dependency uses a new and acceptable license. Adding that license to the whitelist can be done on-demand as part of adding that dependency. That's how I would tackle (defer) the process at least.

**Comment by codefromthecrypt** [comment]
Thanks @michaelsembwever and @WillemJiang I think there's still a question we need to answer, still

package.json includes utilities such as the linter (eslint) which are used as binaries. These are in the section called `devDependencies`. Since there's limited time to spend on all types of work, it would be nice for a mentor to acknowledge if we must or must not hunt down even GPL usage when it is used as a binary. My assumption based on experience is we don't. For example, we don't scrutinize shell commands that include references to GPL linux tools.

**Comment by jorgheymans** [comment]
As we backed out of the apache.org migration, this is no longer relevant.
