### ISSUE TITLE
Grok what exactly we are supposed to do about "official release"

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2597]
Right now, the quick start section of our README includes a script that downloads "convenience binaries" which are built directly from voted source published under apache group IDs. It also includes links to a docker image also built from the exact same binary.

Later in the README, there's a mention of the source release, and the formal location of the "convenience binaries" the above are built from.

There seems to be some problem with this in @nacx opinion, which I'm personally having a hard time following as it refers to things like "download page" when we are talking about a README file. That or we aren't talking about the same thing.

Anyway this issue will hopefully track what if any change our README has to make to comply with whatever rule we have broken.

Here's the thread: https://lists.apache.org/thread.html/a7a9d52b91128a932329448a3fda62a077a6c94ccfec0e734ef30722@%3Cdev.zipkin.apache.org%3E

@michaelsembwever @wu-sheng @reta @WillemJiang please help resolve what we are required to do here.

**Comment by codefromthecrypt** [comment]
FWIW this is one of the various recent threads from the incubator on this topic. https://lists.apache.org/thread.html/cd79b79de1b6650e465c4c9d9a3a5cba681f10e38ac75edf5dca3be7@%3Cgeneral.incubator.apache.org%3E

if we are to take action, I'd like to know specifically what has to change and to what, and who else thinks that we should before we do it. We've had an arduous time with arbitrary rules in the past, so it is a hot topic for me personally.

**Comment by nacx** [comment]
So, there was a misunderstanding in the thread, regarding what we were discussing. In my feedback on the last release vote, I provided a set of items I'd like to see in both, the README and the website.

* The comments on the README have been addressed.
* The comments about the website still need to be done, and that's what I was referring to in the thread. Apologies if I was just asked specifically for the README bits and I answered about a different thing.

This stuff is something I said I like to see _in future releases_, so I don't think everything should be fixed for the next one, since I don't know if the community is actively working on the website or it is something that will be done in future phases.

For completeness, and to make it crystal clear, the README LGTM. The bits I think that need to be added to the website are:
* A download page in addition to the quickstart one with links to the official Apache release (which are the source archives) as the first option. To quote an example from [LEGAL-270](https://issues.apache.org/jira/browse/LEGAL-270), _All official Apache releases are in source form; Docker images can be built from our official source releases, but are derived distributions analogous to, say, Debian packages_. So when we say official releases, we refer to the source archives the PMC votes upon.

That's it. The main project website should have pointers to the official Apache source releases. Currently it only has the Quickstart guide and newcomers coming to Zipkin reading the website to learn about the project will just see the Docker image, the built jar, and a link to Github (that host the source archives for the tag, wihch is not exactly the same as the ASF source release as voted and published to the ASF repos).

**Comment by codefromthecrypt** [comment]
Thanks, post ASF we have no "move issue" access anymore. I'll create an issue on https://github.com/apache/incubator-zipkin-website/ and close this one out.

Mentors: save your time! this is about the website which hasn't had any work done around this at all. we are same page now.

**Comment by codefromthecrypt** [comment]
closing for https://github.com/apache/incubator-zipkin-website/issues/12

**Comment by codefromthecrypt** [comment]
I also opened another thread for incubator team to please make things easier on us. https://lists.apache.org/thread.html/e0a7974b5bbe61388e3921be2feb5ce458dc7e7e3597b9eaace1de54@%3Cgeneral.incubator.apache.org%3E
