### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by fbeaufume** [openzipkin/zipkin#2798]
TLDR: despite "--logging.level.zipkin2=TRACE" I get no logs.

The server is launched with "java -jar zipkin-server-2.16.2-exec.jar --logging.level.zipkin2=TRACE" as described in https://github.com/openzipkin/zipkin/tree/master/zipkin-server . The standard output displays some logs during Zipkin server startup, but after that nothing.

Then I feed the server with traces and successfully display them in the Lens UI, but the standard outup does not display any additional log.

**Comment by jeqo** [comment]
Hi @fbeaufume 

As far as I can tell `zipkin-server` core logic is not logged out. From source-code you can see that logging is mostly enabled on pluggable components as storage and collectors, if you're expecting to see something specific, check here https://github.com/openzipkin/zipkin/search?q=LoggerFactory.&unscoped_q=LoggerFactory where we use logging and if something doesn't look right, please open an issue.

If you're using memory storage (default), then you'll probably not get much logs tho. To check loggers level: http://localhost:9411/actuator/loggers e.g. if you want to enable ALL logs, try `--logging.level.ROOT=TRACE`

If you're interested on `zipkin-server` logic behaviour, I'd recommend to look at metrics we expose instead of logs: http://localhost:9411/actuator/prometheus or http://localhost:9411/actuator/metrics or self-tracing capabilities. We focus on making zipkin easier to operate, and metrics and self-tracing seems enough for it. For debugging we have testing. Adding more logging on this component is not something we have received much requests about and personally I don't think it will get prioritize on the short term.

**Comment by fbeaufume** [comment]
Thank you @jeqo for the feedback.

I guess this is not a bug anymore, but maybe a feature request to add some logs, or in the mean time mention in https://github.com/openzipkin/zipkin/tree/master/zipkin-server that no logs are produced by the core and the in-memory storage.

**Comment by jeqo** [comment]
IMO I don't think it's worth mentioning we don't log a component, the same way we don't mention when we do log them.

As mentioned earlier, test-cases are enough for explaining behavior, debugging and reproducing errors we should fix; I won't expect someone adding logs just for the sake of logging. If you would like to add logging on a specific part, please raise an issue to discuss the actual problem.

**Comment by sebastianhaberey** [comment]
Just reporting in to say that I fell for this today. Tried to log incoming queries by setting `QUERY_LOG_LEVEL: DEBUG` as described on https://github.com/openzipkin/zipkin/tree/master/zipkin-server. Got nothing. I'm also using the in-memory storage, so I'm guessing it's the same thing.

**Comment by shakuzen** [comment]
@sebastianhaberey Looking at the latest code, it does seem `QUERY_LOG_LEVEL` does not do anything. We probably missed updating the README when that change was made. Would you mind opening a separate issue or a pull request about that?
Depending on what kind of logs you are looking for, perhaps https://github.com/openzipkin/zipkin/issues/2680 is what you want.
