### ISSUE TITLE
ES health check should block on schema creation

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2825]
There's a race condition where a POST could leak prior to elasticsearch storage's schema being fully initialized. It leads to query errors like this:

```
java.lang.IllegalStateException: response for aggregation failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"zipkin:span-2019-09-26","node":"Htub5Z_6Rp2gARM-ckCj6Q","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}},"status":400}
    at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[zipkin-storage-elasticsearch-2.14.2.jar!/:?]
    at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:78) ~[zipkin-storage-elasticsearch-2.14.2.jar!/:?]
```

Notably, this is possible when there are multiple collector nodes.. basically the index template could be in the process of being applied on one node while the other checks, and that lets a POST through which is now not indexed properly.

The reason is that the health check doesn't initialize the index templates, such as we do in cassandra. The fix is easy, but for those who need a workaround now, hit `/api/v2/autocompleteKeys` instead as eventhough it returns a constant (no perf impact), it does the init logic needed first (ensures index templates).

Thanks @basvanbeek for noticing this. cc @openzipkin/elasticsearch

**Comment by dio** [comment]
@adriancole to clarify, is it OK to use `/api/v2/autocompleteKeys` as readiness probe for other storages as well?

**Comment by codefromthecrypt** [comment]
other storage work properly

**Comment by codefromthecrypt** [comment]
what I mean is only ES allows an early write to catastrophically affect query.

in both mysql and cassandra we have offline instructions to add the schema. only cassandra also can self-install it. However, there's no situation like this in cassandra either about a sneaky write killing things.

This is a bug in so far as the health check doesn't ensure schema. However, the way ES behaves adds to the concern. I talked with @basvanbeek about making a commandline option to display what the index template should be. Right now, only ES doesn't have a way to create the schema at setup time (without starting and stopping a zipkin server). This is due to the amount of compatability issues in ES and also that certain parameters are site specific. OTOH, we could probably make a static one that people can hand tune. As far as I know this problem would never occur if there was no possibility of a race in data entering vs index template creation.

wdyt @anuraaga

**Comment by codefromthecrypt** [comment]
@openzipkin/elasticsearch does anyone know how to work around an error like this when a write sneaks in before the index template finishes initialization? There's some eventual consistency issue that leads to this. Ex a GET succeed while a PUT is in progress on another host or before it applied. When that passes a POST can be written without the template, poisoning the index. This is the hyphothesis as in a case where this happened we noticed the index template is actually correct.

```
java.lang.IllegalStateException: response for aggregation failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"zipkin:span-2019-09-26","node":"Htub5Z_6Rp2gARM-ckCj6Q","reason":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.","caused_by":{"type":"illegal_argument_exception","reason":"Fielddata is disabled on text fields by default. Set fielddata=true on [traceId] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."}}},"status":400}
    at zipkin2.elasticsearch.internal.client.HttpCall.parseResponse(HttpCall.java:151) ~[zipkin-storage-elasticsearch-2.14.2.jar!/:?]
    at zipkin2.elasticsearch.internal.client.HttpCall.doExecute(HttpCall.java:78) ~[zipkin-storage-elasticsearch-2.14.2.jar!/:?]
```

**Comment by anuraaga** [comment]
Just to confirm, by health check we're referring to `ElasticsearchStorage.check`? It indeed only checks whether the index is available. Other endpoints like `spanStore` all ensure index templates. But I'm not sure if adding that to health check would change anything - right now, parallel calls to `spanStore` have a race between ensuring indexes, but otherwise parallel calls to `check` would have a similar race IIUC.

This documentation implies that index creation does take some time to propagate to shards

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html#create-index-wait-for-active-shards

My relatively wild guess is that nodes that have had the template propagated to them will respond to the `get-template` request successfully even when other nodes have not created it yet. And now that we're actually round-robining, this means `get-template` can succeed on a node but the span is sent to a following node where it hasn't succeeded yet. One shard will index spans with the template, the other will not (until the next day though when a new index is created, heh). This behavior seems quite dangerous, but I guess to solve it, it would be nice to have an option when indexing to wait for any pending template operations in the cluster which I don't see at https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html 

Looked through elastic docs to see if they provide a simple way to know status of index templates better (a scatter-gather as we've been implementing recently? ;) ), but can't find any. Simplest way to solve might be to just make sure our `get-template` call succeeds on all endpoints in an `EndpointGroup`.

https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/elasticsearch/src/main/java/zipkin2/elasticsearch/EnsureIndexTemplate.java#L37

Hopefully someone else can also check that this understanding makes sense.

**Comment by codefromthecrypt** [comment]
I think you are right that moving this up wont solve all possible problems
but it would reduce them.

for example if there is no chance a node goes in service without the index
template at least attempted, we are better off.

agree the main issue is there isnt a way to block on completion and also it
is a coordination issue. for example some sites manually control the
template. this means we can't do a content check.

the idea of a fan out on nodes is possible but also not sure the
implications of that and also the overhead..

**Comment by codefromthecrypt** [comment]
simultaneously I am working on a cheap cli to make a version specific
template for manual installation based on same env variables

**Comment by codefromthecrypt** [comment]
one last thing.. it would be great for ES to create a consistent barrier
for templates. however we still need something now as new features aren't
always back ported.

**Comment by anuraaga** [comment]
A CLI for uploading the template for users of multiple nodes is probably the best way anyways :)

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/zipkin/pull/2827 does the scary work. I think it could be an easy change to make a CLI for someone familiar with java
