### ISSUE TITLE
CI our docker setup

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#2850]
in zipkin-gcp master fails if there's a problem in docker. We should fail here, too.

super points for also failing if basic k8s setup fails per https://github.com/openzipkin/docker-zipkin/issues/232

**Comment by anuraaga** [comment]
Just to confirm, is this the "run a smoke test" against the Docker image, which we started doing for `openzipkin/zipkin`? I think @saturnism is working on it for `zipkin-gcp` :) Getting the breakage notification from `zipkin-gcp` would be simple, syncing that status back to cause a failure here might be tough and I'm not sure if it's worth much.

**Comment by codefromthecrypt** [comment]
sorry I didn't mean to test downstream. I meant the same sort of smoke test that is in zipkin-gcp, to do it here on master build. A simplified version as we don't need to integrate much.. maybe just hit health check with elasticsearch storage (or even not elasticsearch) https://github.com/openzipkin/zipkin-gcp/blob/master/travis/publish.sh#L107

**Comment by anuraaga** [comment]
Ah yeah we have that smoke test for the normal build too in zipkin-gcp. That isn't our docker setup though, just runs the jars. @saturnism is working on doing similar for the docker setup in zipkin-gcp.

In this repo, it's the opposite :) We don't run any smoke test on the jars, but do run it on the docker image

https://github.com/openzipkin/zipkin/blob/master/docker/docker-compose.test.yml

After getting closer to the end of the migration, was going to send an email or such notification to the members that they should go to Docker Hub settings to turn on notifications for build failures, to see the errors for that test. I think it also would mark the commit with a failure on GitHub (the red X instead of green check) but not sure since we haven't had a docker smoke test failure yet.

Is there anything else you have in mind?

As for k8s, sounds like a beast ;)

**Comment by codefromthecrypt** [comment]
I suppose I mean invoking docker-compose.test.yml automatically. let's update this issue or close it once that happens.

k8s is maybe a beast, but that's also the world we're in. I have no idea how it starts in such a way that screws with the path of zipkin, but that's a good reason for a smoke test IMHO. that or we can just start docker with a wonky path..

**Comment by anuraaga** [comment]
Yeah Docker Hub automatically invokes docker-compose.test.yml after building the image, and if that fails, it won't push a tag and will send a failure notification. So probably already good there.

Agree it's nice to smoke test kube too - because it's a beast will take some thought on a good way though.

**Comment by codefromthecrypt** [comment]
ic that's good.. maybe though people ignore notifications. I know I ignore perpetually failing ones. I think we should kill the build here if possible, as that makes it impossible to ignore. unless we think that there is a reason to publish a snapshot with a failing image, or that the time to create it will be too long.. 

(ps we should check both zipkin and slimbo)

**Comment by codefromthecrypt** [comment]
from @devinsba 

> Kubernetes is using this to test Kubernetes, I think we could spin a parallel build on travis to test it: https://github.com/kubernetes-sigs/kind

**Comment by anuraaga** [comment]
To add color to this, the original kube breakage we wanted to fix did not repro on Google Kubernetes Engine or kind. It seemed to have to do with platform-specific way of setting up container filesystems, which reprod on docker desktop kube, and possibly others if they use a similar scheme. Interestingly it reprod with docker itself after just installing kube, which mucked with file systems.

Given all the variables, I don't know how much value testing with something like kind will add, it implements everything using docker so has very similar behavior to `docker run`, which we're already testing via the compose file.

**Comment by codefromthecrypt** [comment]
agree k8s testing wouldn't have caught this. it was an issue on os/x after k8s installed on docker for mac, and probably wouldn't happen after reboot either. Once it mucked the system, the same problem existed in normal docker, so normal docker is good enough as we aren't supporting docker itself, just our build of zipkin.

**Comment by codefromthecrypt** [comment]
When #3238 is in, basic tests on all our images will be done in github actions (via HEALTHCHECK). This is a bit more transparent than what we had before, even though the before was cool in another way (testing composite containers). Regardless, I think this will be a decent base to progress from.
