### ISSUE TITLE
Orphaned spans causing UI issues

### ISSUE THREAD

**Issue by lambcode** [openzipkin/zipkin#2922]
## Describe the Bug
I'm not sure that orphaned spans is the correct term here, but I'm going to use it to describe a span that does not have a parent span but is still part of a complete trace. These orphaned spans are very difficult to differentiate from other spans, and they seem to cause problems with the current lens UI.

## Steps to Reproduce (zipkin 2.19.1)
1. Open this saved trace in lens UI [exampleTrace.json.txt](https://github.com/openzipkin/zipkin/files/3848574/exampleTrace.json.txt) (saved as txt for github compatibility)
2. Collapse the root span
- Note that the orphaned span does not get collapsed
- Note that the orphaned span appears like a child span of the root span

## Expected Behaviour
This is up for discussion, but what I'd like to see is orphaned spans to show up as siblings to the root span in the tree. I would also appreciate it if these spans were somehow marked as orphaned. As for the collapsing behavior, I would expect that collapsing the root span does not collapse these orphaned spans, but if the 'collapse all' button is used then all spans would be collapsed leaving just the root span and the orphaned span roots visible.

**Comment by jcchavezs** [comment]
@tacigar do you have some time to check it?

**Comment by tacigar** [comment]
Thank you for your report.
I think showing up orphaned spans as siblings to the root span is most reasonable.

**Comment by tacigar** [comment]
I investigated code which builds trace tree.

https://github.com/openzipkin/zipkin/blob/8a5609a44ea52fa85d5309d7e4e46bc70a4c3ca8/zipkin-lens/src/zipkin/span-node.js#L272-L276

In the current implementation, all orphaned spans will be children of the root span...

**Comment by tacigar** [comment]
I still don't know the best way to draw graphs which contains orphaned spans.
However, according to the code comment above, I think that orphaned spans should be drawn as children of the root span anyway.
Of course, the current behavior when collapsing orphaned spans is a bug, so I will fix it first.

**Comment by jorgheymans** [comment]
@tacigar can this be closed since https://github.com/openzipkin/zipkin/issues/2922 was merged ?

**Comment by jorgheymans** [comment]
Comparing latest 2.19.1 (left) with 2.22 (right):

Not collapsed:

![image](https://user-images.githubusercontent.com/193792/97023744-3c6bca80-1556-11eb-9860-abc5a812aa25.png)

Collapsed:

![image](https://user-images.githubusercontent.com/193792/97023826-5ad1c600-1556-11eb-8aa8-d34c0df05bd4.png)

@lambcode are you ok with this ? It's not what you asked for, but I guess not many people will know they're dealing with an orphaned span when it would not collapse along with the root, or what it evens means to have an orphaned span or what is causing it (instrumentation bug?).

My feeling is that from the UI side it should collapse with the root span since we're showing it as part of said root span anyway and it is connected to it. Anything else would be surprising to the user. Maybe a visual indication that the span is orphaned, but if we do so then we need to explain what it means. But i'm afraid we'ld be confusing people ? 

There is a more general issue on detecting common data issues that maybe this could be part of: https://github.com/openzipkin/zipkin/issues/1484 ? WDYT ?

**Comment by lambcode** [comment]
The behavior shown does seem better than it was previously (no longer looks like a UI bug). I do wonder how orphaned spans would show if the root span is missing from the trace.

Long term, it would be nice if there was an indication that the trace contains orphaned spans and what those spans are. Without an indication it is easy to be unaware of instrumentation issues that cause them. If doing so is rolled up into #1484, that seems reasonable.

**Comment by jorgheymans** [comment]
Thanks for the quick feedback @lambcode , going to close this issue then. There's a link to the common UI issues so we can backtrack here once it gets implemented.
