### ISSUE TITLE
How to use jaeger's UI to read data from the elasticsearch written by zipkin.

### ISSUE THREAD

**Issue by uckyk** [openzipkin/zipkin#2951]
We currently use zipkin to collect data (jaeger does not support Dubbo). ES stores zipkin data. I know that zipkin and jaeger have different data formats. Maybe I need to set up a query service and then go to ES to query. (I don't know how to build it)
I would like to know if jaeger provides such tools for data conversion between zipkin and jaeger.

I am a beginner, thank you very much！！！

**Comment by yurishkuro** [comment]
Jaeger can integrate with Zipkin instrumentation at the collection API, i.e. `jaeger-collector` can accept spans in Zipkin format (json, thrift, and proto). But it does not integrate with implementation details of Zipkin such as storage formats (or even query service API) because of the difference in the data models.

**Comment by uckyk** [comment]
> Jaeger can integrate with Zipkin instrumentation at the collection API, i.e. `jaeger-collector` can accept spans in Zipkin format (json, thrift, and proto). But it does not integrate with implementation details of Zipkin such as storage formats (or even query service API) because of the difference in the data models.

You mean Jaeger collector can collect the data reported by Zipkin, but their data model is different.

Now, I use Zipkin client to send data to Kafka (HTTP is not allowed by the company), consume Kafka data through Jaeger server, and then store it in ES. Finally, use the Jaeger UI to show it. Is this solution OK?

Is there another better solution? Thank you very much.

**Comment by basvanbeek** [comment]
I'm going to close this issue here as the ask is now outside the scope of the Zipkin ecosystem. 

Zipkin provides a propagation format (B3) and a data model (API v2: https://zipkin.io/zipkin-api/).  These models are open and for everyone to integrate with. 

If you are dead set on using the Jaeger UI instead of the Zipkin Lens UI while using Zipkin instrumentation you will have to find or write a Jaeger specific collector that listens on Kafka and understands Zipkin data model payloads.
