### ISSUE TITLE
Download JSON via UI

### ISSUE THREAD

**Issue by connectwithnara** [openzipkin/zipkin#3055]
We find it useful to have the `JSON` button in the Lens UI also to download the raw data for a trace.

**Comment by codefromthecrypt** [comment]
I think this is in? @anuraaga @tacigar ?

**Comment by anuraaga** [comment]
Yeah you can see the screenshot in this PR with a Download JSON button - https://github.com/openzipkin/zipkin/pull/2985

We have had some discussion about whether we should move that next to the upload JSON button, which may be causing confusion here. But since the upload JSON button is valid anywhere, hence in a global layout, and the download JSON is only valid in the context of a trace, hence in the trace page layout, they're in different locations. I can think of pros/cons of both, and not being a UX person not sure if I can decide 😅

**Comment by jorgheymans** [comment]
Indeed, added here https://github.com/openzipkin/zipkin/commit/08cee5023bf6e24c277bce85839ad1c043230f63 and thus available from zipkin-server 2.19.3 onwards
