### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin#3177]
There is no (obvious) way to see all the changes from different versions of Zipkin. 

There should be a CHANGELOG file with the usual information about bugfixes, new features and breaking changes, whenever a release happens. There should also be a short mention of the changelog in the readme.

**Comment by codefromthecrypt** [comment]
we use releases for this https://github.com/openzipkin/zipkin/releases

**Comment by ghost** [comment]
I see just a release for 2.21 (with the tag 2.21.1). Now we are on 2.21.7 and I can't see the changes since this. 

How urgently should I update? Are there critical bugs that have been fixed? I cannot determine with a short glance whats going on. Sometimes there are notes (e.g. for 2.19.2), often not.

**Comment by codefromthecrypt** [comment]
we're about to release a 2.22 and catch-up notes since last release then. it is possible to use git compare to tell differences between then. I don't expect anyone to want to do more than this.

**Comment by codefromthecrypt** [comment]
meanwhile you can look like this if unsatisfied or ask us on https://gitter.im/openzipkin/zipkin 

https://github.com/openzipkin/zipkin/compare/2.21.6...2.21.7

**Comment by codefromthecrypt** [comment]
PS we don't always cut release notes until a later patch. ex 2.19.2 as it is important that the inner circle verifies before we notify people with a release. it is intentional. We only do release notes for minors unless there's a good reason not to, and also this is to do with effort levels as this is a completely volunteer project.
