### ISSUE TITLE
Is RocketMQ and PostgresQL supported

### ISSUE THREAD

**Issue by XiaoChuangGitHub** [openzipkin/zipkin#3266]
Would you like to know which of these two support or neither?Where can I check my data

**Comment by codefromthecrypt** [comment]
please use https://gitter.im/openzipkin/zipkin to chat, but don't duplicate issues.

#2620 is for rocketmq
#1232 is for PostgresQL

You can add your interest on these issues.

both would need someone to help create and maintain the support. PostgresQL would be much more work because storage is more difficult. Please reply on https://gitter.im/openzipkin/zipkin if you want to chat more.
