### ISSUE TITLE
TLS issue with Docker healthcheck

### ISSUE THREAD

**Issue by nkvaratskhelia** [openzipkin/zipkin#3424]
When running Zipkin with TLS enabled as a docker-compose service (using the following env var: `- JAVA_OPTS=-Darmeria.ssl.key-store=keystore.p12 -Darmeria.ssl.key-store-password=password -Darmeria.ssl.enabled=true -Darmeria.ports[0].port=9411 -Darmeria.ports[0].protocols[0]=https`), the server starts up and the UI works with https, but zipkin logs the `Caused by: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST` exception stacktrace every 5 seconds and the log size grows quickly.

It seems there's a docker healthcheck which only targets the http endpoint:
https://github.com/openzipkin/zipkin/blob/master/docker/Dockerfile#L70
https://github.com/openzipkin/zipkin/blob/master/build-bin/docker/docker-healthcheck#L46

Expected behaviour:
The healthcheck endpoint should be dynamic, based on which protocol is enabled (http/https).

**Comment by codefromthecrypt** [comment]
We can only support things that are top-level config via ENV variables, even if things passed through java opts or spring config might work.

In other words, trying to detect this config via scraping JAVA_OPTS or spring properties.. and handle it in the health check... it won't likely work out well. Meanwhile, trying would add technical debt to the maintenance responsibilities here.

I would recommend you overwrite the docker-healthcheck on the image via a new image, volume mount or otherwise. K8s won't read it anyway.

**Comment by codefromthecrypt** [comment]
ps anyone who has a workaround to share, please comment here!
