### ISSUE TITLE
App not communicating with Zipkin after enabling SSL in Zipkin

### ISSUE THREAD

**Issue by LakshmanKumar522** [openzipkin/zipkin#3511]
After enabling SSL in Zipkin (Version: 2.23.16) with the self signed certificate the application is not sending the traces info to Zipkin.

The web application [uiapi] appears to have started a thread named [AsyncReporter{RestTemplateSender{https://url of Zipkin/api/v2/spans}}] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.8/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
 java.base@11.0.8/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
 app//zipkin2.reporter.ByteBoundedQueue.drainTo(ByteBoundedQueue.java:81)
 app//zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:270)
 app//zipkin2.reporter.AsyncReporter$Flusher.run(AsyncReporter.java:378)
 java.base@11.0.8/java.lang.Thread.run(Thread.java:834)

**Comment by NImboNagatory** [comment]
if you are using nginx. it might be redirecting the traces. in my case i checked /var/log/nginx/access.log.1 file.

**Comment by codefromthecrypt** [comment]
@LakshmanKumar522 we have a [test in this repository](https://github.com/openzipkin/zipkin/blob/master/zipkin-server/src/test/java/zipkin2/server/internal/ITZipkinServerSsl.java) for self-signed, but it is hard to diagnose what's going on in your case, because you are using a "sender" not written in this org at all (RestTemplateSender, so likely spring-cloud-sleuth?).

If it were written in this org, I would suggest an integration test that uses our docker container and sets up the self-signed cert, sharing details needed between the client and the server. If that passes (likely it would), then as @NImboNagatory suggests look at other infrastructure that might contribute to it.

Meanwhile, I have to close this issue as we already have a test, and wouldn't add another on a library not maintained in this org.
