### ISSUE TITLE
Update netty to 4.1.86.Final to remediate CVE-2022-41881

### ISSUE THREAD

**Issue by debraj-work** [openzipkin/zipkin#3512]
zipkin is getting flagged in our security scans due to the presence of `io.netty:netty-codec-haproxy:4.1.78.Final` which has [CVE-2022-41881 ](https://nvd.nist.gov/vuln/detail/CVE-2022-41881) .

Is there any plan to upgrade `io.netty:netty-codec-haproxy` to `4.1.86.Final` to get around this?

**Comment by rweinsteinPGH** [comment]
My organization tagging this as well, i know netty just got updated a few months ago to 4.1.78 but needs to get updated again to clear this issue, severity is High

**Comment by jcchavezs** [comment]
Ping @llinder

**Comment by debraj-manna** [comment]
@jcchavezs @llinder - Can you please let us know if zipkin is really effected by [CVE-2022-41881](https://nvd.nist.gov/vuln/detail/CVE-2022-41881) ?

**Comment by darkmastermindz** [comment]
Hi @jcchavezs @llinder

This CVE seems to be inherited from Spring Boot and resolved in [Spring Boot v2.7.12](https://github.com/spring-projects/spring-boot/releases/tag/v2.7.12).

I can confirm this is being picked up on my end as well as the only CVE left to remediate in [Zipkin 2.24.2](https://github.com/openzipkin/zipkin/commit/3575817a1d208b1444ba5b9b8ed6fd398b76df34) although it uses v2.7.12 since it's specified in https://github.com/openzipkin/zipkin/blob/1acbc8651df50aa8200cbff725285a1cb1c759d9/pom.xml#LL57C1-L58C1

Opened PR with using netty 4.1.92.Final to match to see if there are any conflicts.

References: 
[spring-projects/spring-boot/issues/33580](https://github.com/spring-projects/spring-boot/issues/33580)

**Comment by darkmastermindz** [comment]
@jcchavezs @llinder I think we should favor should bumping to 4.1.92.Final #3548 to match the current Spring Boot version. 
Wanted to compare with the CI with 4.1.86.Final in #3549 - @shakuzen mentioned that there was a test broken unrelated to this change.

**Comment by codefromthecrypt** [comment]
latest version of zipkin has all netty CVEs addressed
