### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [openzipkin/zipkin#3536]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@iieitaimus) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by jcchavezs** [comment]
Please use this link https://github.com/openzipkin/zipkin/security/advisories/new, also if you are up to, could you create a `SECURITY.md` file like in https://github.com/corazawaf/coraza/blob/main/SECURITY.md ?

**Comment by codefromthecrypt** [comment]
I've been AWOL for over three years, but I'm back for a bit and will help craft a SECURITY.md. Especially, we need to re-engage site owners into maintenance positions, so that these are actually looked at.

Also, clarify that by release policy all dependency versions are updated or documented why not before any and every release. I noticed a lot of "whack a mole" library bumps as well maintenance of indirects instead of fixing the direct. This are could be clarified both in expectations and how to keep the advisories thing free of library bumps and focused on practice and code in this repo.

my 2p

**Comment by codefromthecrypt** [comment]
we've clarified our security process here, which is less than what you'd expect for a commercially staffed operation, yet more than most ad-hoc groups I suspect. https://github.com/openzipkin/zipkin/blob/master/SECURITY.md
