### ISSUE TITLE
PostgreSQL DbConfig with SSL set to false still uses SSL

### ISSUE THREAD

**Issue by klette** [openzipkin/zipkin#399]
The PostgreSQL enables SSL by the mere presence of the ssl-key in the connection string.
This is true for both the 8.4 and 9.1 drivers mentioned in Project.scala.

The patch should be quite trivial, something on the lines of this in DBConfig.scala

``` scala
 "jdbc:postgresql://" + dbp.host + dbp.getPort + "/" + dbp.dbName + "?user=" + dbp.username + "&password=" + dbp.password + (if (params.ssl) "&ssl=true" else "")
```

**Comment by codefromthecrypt** [comment]
Closing this issue a we are removing PostgreSQL from the default list. Since we don't run tests or allow docker configuration, PostgreSQL may already be broken without us knowing: #853

In the near future, we will release an alternative to anorm, jOOQ, in the [java project](https://github.com/openzipkin/zipkin-java/blob/master/zipkin-java-jdbc). If there's enough interest to contribute docs and tests for other databases, we can always pick this back up.
