### ISSUE TITLE
web DefaultQueryLimit is not overridable

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#462]
`Constants.DefaultQueryLimit` is a hard-coded val. Seems at least this should be overridable by a flag, right?

https://github.com/openzipkin/zipkin/blob/master/zipkin-web/src/main/scala/com/twitter/zipkin/web/Constants.scala#L19

see #443

**Comment by codefromthecrypt** [comment]
@mosesn pls suggest a preferred approach and I'll ensure that the internal twitter deployment of zipkin-web has a default query limit of 100.

ex.

``` scala
  val queryLimit = flag("zipkin.web.query.limit", 10, "Default query limit for trace results")
```

**Comment by mosesn** [comment]
that style works well for me.  I'm not sure that 10 makes sense though–did you guys discuss what your main use cases are at the workshop?

**Comment by codefromthecrypt** [comment]
10 was already decided by majority on the other pull request and don't want
to start a bikeshed on that. I just wanted to make sure you can have the
default you want inside Twitter.

**Comment by mosesn** [comment]
What do you mean majority?  I didn't see anybody express a strong opinion other than me and noslowerdna?

**Comment by mosesn** [comment]
Oh, you merged that in?  Why did you do that without discussing it?

**Comment by codefromthecrypt** [comment]
We don't have to further discussion about a default value, when it can be
overridden. You are the only person who asserted further discussion was
needed.
You made the case about why you want default to be 100. The originator made
the case about 10 and the act of merging that was seconded by rtyler and
implicitly me.

This is OpenZipkin: we haven't made a rule that we need 100% consensus. Nor
can we force people to discuss something they are not interested in
discussing further.

Resolving this issue will allow you to have the value 100 and if later the
community wants to change the default to 101, we can do that. In the mean
time, we really do have bigger fish to fry.

**Comment by mosesn** [comment]
If you've decided unilaterally to ignore discussion, it seems like it would be polite to say, "This is a bikeshed, I don't want to discuss it any further" rather than, "OK, let's open it up for discussion, does anyone else have something to say" and then merging without actually discussing it.

I'm bothered that I thought we were having a discussion about what zipkin is for, and the face it should provide to folks who are new, and I felt like it was signaled to me that it was indeed important (and indeed, someone made a PR about it!) and then there was a total about-face without any real discussion.  The default _is_ important, because when folks try out zipkin, and try to see if it's useful, they'll see the default.

**Comment by codefromthecrypt** [comment]
Moses, there was no discussion for 2 weeks, despite an attempt to encourage folks to do so. There was no unilateralism, as two others besides me indicated they wanted the change. I can tell you aren't satisfied; I'm disappointed that I couldn't please you even by raising this issue.

**Comment by rtyler** [comment]
@mosesn I threw a :+1: in on what looked like a pull request that had been stalled, but was completely merge-able..

The questions raised in the pull request:

> A. Why doesn't latency scale linearly with the number of items we're fetching?
> B. What are the main use-cases of zipkin, and which of them should we optimize for?
> C. How much do zipkin users care about latency? What is acceptable?

I think these are great questions to ask and discuss in terms of overall direction for Zipkin, but I do not see them as show-stopper questions for merging a very minor pull request. From the outside-looking-in on a number of projects, it's always encouraging to see my pull requests merged, even if they do spawn subsequent work (like that captured in this ticket). IMO this is important to foster a good community of contributors.

I think this issue is a good example of how to handle things like this. It was a clearly minor change but as has been raised, defaults are important (of course, until this issue is resolved it's not a default so much as a _constant_). That's not something a casual contributor should be deadlocked in, otherwise the project likely will lose them forever.

Personally, I think the best way to answer those questions (A, B, C) is to get releases built and start getting feedback from other users which have not traditionally participated in the project

**Comment by mosesn** [comment]
@adriancole and I resolved our disagreement off-list, and we agreed that my questions on that PR were out of scope for the change.

@rtyler I agree that we should be working to make sure contributors feel welcome, and that being able to merge a PR quickly is a great way to get a contributor excited about the project.  At the same time, I'd appreciate it if we're explicit about why we're not going to address a concern.  I would have deeply appreciated the explanation you just provided on PR 443.

**Comment by rtyler** [comment]
@mosesn duly noted 

![roger that](http://orig15.deviantart.net/1416/f/2009/003/7/0/roger_that_kitty_cat_by_zoegirl101.jpg)

**Comment by codefromthecrypt** [comment]
Here's the style of argument that supports this: `-zipkin.web.query.limit=100`
