### ISSUE TITLE
Eliminate dependency on Scala compiler and runtime

### ISSUE THREAD

**Issue by b** [openzipkin/zipkin#463]
Many Java-centric companies prefer to avoid alternate JVM language dependencies. Rewriting components as required to eliminate the Scala dependency of Zipkin would be valuable to them.

**Comment by rtyler** [comment]
I'm generally in favor of this. For my own understanding, what overlap does this have with [brave](/openzipkin/brave)?

**Comment by codefromthecrypt** [comment]
:+1:

I suspect if we do this well, we can provide a future without the need to maintain both zipkin and brave separately.

**Comment by eirslett** [comment]
There's some confusion about what should actually be rewritten... It would be a lot of effort to port the whole Zipkin code base to Java, just to get rid of the Scala dependency inside query/collector/web.
What we discussed at the workshop was to extract the "Tracer" client from finagle, rewrite it in Java and then use that?
Our use case at FINN was that we wanted to use Zipkin without having Scala in all our ~300 applications. Collector/query/web are 3 projects that are written in Scala anyways (using the Scala ecosystem and maintained by Scala developers) so that's not a problem at all.
I really don't want to see Zipkin rewritten with Spring/Struts/Hibernate etc...

**Comment by kristofa** [comment]
@eirslett I don't think this issue is about rewriting the back-end services (query/collector/web). If we release / package / document these properly I guess they are fine. I agree that there is no reason why these should be rewritten.

I agree that our goal should be to have 1 Java "core" implementation that can be integrated in Finagle and that could serve as a base layer for the existing brave integrations (jersey, resteasy,...).

**Comment by eirslett** [comment]
@b can you clarify a bit, is the Scala reluctancy about not wanting the Scala dependencies in their business applications (very understandable) or is it about not wanting to deploy Zipkin at all because Zipkin is written in Scala? (somewhat less understandable)

**Comment by michaelsembwever** [comment]
During the workshop there was also the discussion about replacing traits with java interfaces, which is what this issue is a spin-off from.
 ref: https://github.com/openzipkin/zipkin/issues/451

This discussion went beyond that of just avoiding the scala dependency in client libraries, but providing better compatibility within the server-side zipkin stack.

Today it isn't possible to write your own collector or query implementation
with just pure java. This is going to hold us back from building a community of active developers. And indeed we saw @NiteshKant talk about Netflix writing their own Zipkin because the server-side components were all scala.
  ref: https://github.com/openzipkin/zipkin/issues/451#issuecomment-119854512

This ticket needs clarification as to what it involves, and the broader
discussion be cleanly split between simplifying the client-side and simplifying the
server-side.

**Comment by eirslett** [comment]
@NiteshKant could you please clarify a bit what Netflix' point of view is (or was, regarding the choice of reimplementing Dapper in Java)
You explained at the workshop, but clarification is always nice :-) Was avoiding Scala in the business applications the deciding factor, or is/was it very important that the Zipkin applications themselves were also Java?

**Comment by codefromthecrypt** [comment]
I think this is getting to be mailing list worthy, but at any rate, good
discussion.

The big concern is that there are a few people who want Scala+Finagle impl
to persist.

Can we think about brave? How can we permit can those who can't deploy,
feel limited by, or simply don't like Scala to still be a part of zipkin?
Brave happens to have a subset of features.. Would it be that bad to allow
a java server impl (or golang for that matter)?

I'm guessing the solution is keep the code in a different repo, similar to
brave, so that it doesn't threaten those who still enjoy the current
codebase. Would that work?

**Comment by michaelsembwever** [comment]
@adriancole it's still unclear from your post whether you're talking about the client-side or server-side stack? In context of Brave that's just client-side. 

There are two discussions here.

client-side)
  A) removing scala from client-side libraries.
  B) using common java interfaces in the java client library and in the scala client library.

server-side)
 A-1) rewriting key interfaces (eg zipkin-common) to java to allow new stack components to be implemented in either java or scala, or
 A-2) making existing key interfaces (eg zipkin-common) java-fiendly to allow new stack components to be implemented in either java or scala,
 B) rewriting existing stack components from scala to java to attract more developers into the community.

Brave already solves client-side-A for us.
client-side-B is a "nice to have" in my mind.

I don't think server-side-B is so critical right now. The question of what developers and the community prefers should simply delegate to what is popular and maintained best, as long as we're providing a proper polyglot stack. see my comment in https://github.com/openzipkin/zipkin/issues/451#issuecomment-122296372

Between server-side-A-1 and server-side-A-2 i don't care. Whatever is quickest to implement gets my vote :-)

**Comment by codefromthecrypt** [comment]
OK I will be more clear.

We can break down this task, but I desire to help those writing
instrumentation or backends not require a tree of deps and interop problems.

Brave partially solves that problem, but this isn't just about what brave
chose to solve. I didn't intend to get us down that path. Bear in mind that
many aren't going to desire the Twitter server entrypoint for reasons
including dependencies, but also config management and bootstrap. Consider
netflixoss and others who use spring boot or other means to bootstrap
services. There's also the relative unpopularity of sbt within java
ecosystem, too!

It seems best to allow a java repo to exist regardless of Brave and just
move the corresponding issues there, right? I can count at least 3 folks
who would work on that and so it is more when than if.

Personally, this is of most interest to me as I like my work to be of
highest reuse, and I wish to engage those who have similar interest.
However this is more my morning/weekend work, like the work I did on Brave.
I still have to write Scala at work anyway.

Any reason we shouldn't just move this discussion to a new repo of willing
hands and let them decide what to do?

**Comment by michaelsembwever** [comment]
Having separate repos only really addresses client-side-A as far as i can see…

I'm rewriting zipkin-cassandra from scala to java, under the issue of replacing cassie with the datastax driver, simply because that's the contribution i can give (and it fits cleanly with the datastax driver). Since i can't imagine that this would then mean that the zipkin-cassandra subproject must be moved out into its own repo, along with progress on server-side-A, isn't it inevitable that zipkin becomes a mixture of java and scala? 

The question of sbt is a story for another day, in the server-side-B category.

**Comment by codefromthecrypt** [comment]
I would prefer zipkin to just slowly introduce java where it makes sense.
If preference towards status quo (finagle/scala) interferes with that, I'd
prefer to make a repository in OpenZipkin or DistributedTracing to allow
progress to happen.

I don't expect all backends to be in a mono-repo, as especially people's
local implementations won't be (ex. inside Twitter, we have a Manhattan
storage backend). I don't really want to conflate this issue with the
mono-repo pros/cons though, but it is interesting that cassandra will be
rewritten in java anyway.

On SBT, our build really limits us, and this is only SBT because of scala.
I imagine there will be folks who would prefer to be more productive by
escaping that. Agreed it is another issue, but scala is related.

**Comment by michaelsembwever** [comment]
This issue is still rather unclear as to what it involves

If I've understood you correctly @adriancole you've asking for it to be about client-side-B, and that you'd like to see the work, these java interfaces that both brave and the tracer client library will inherit, in a new repo?

If this issue is to be solely about client-side-B then what about instead of creating a new repo, settle on using interfaces in Brave already? even migrate the scala+finagle implementation over to Brave so that it becomes the "driver" project to zipkin?

**Comment by codefromthecrypt** [comment]
@michaelsembwever the issue as posted doesn't split hairs about client or server side, though I agree it would end up being broken down into work like that. I'm worried that I am dominating the discussion, and in attempts to answer in terms of the options you propose. server-side-B should be possible as an alternate or a rewrite.

We shouldn't conflate this issue with a vote for brave as ideal interfaces for client-side-A. Since this is a new community, it should be a choice how to implement client-side-(A|B), not a force function of current inventory.

We may get more engagement if the community are permitted to build both the server and client side in tandem in a manner they decide to, without the burden of a legacy codebase.

I'd like to hear what others think, and fear that further back/forth on my opinion may reduce the chance others will engage at all.

**Comment by jpinner** [comment]
@eirslett earlier you commented that: 'Collector/query/web are 3 projects that are written in Scala anyways (using the Scala ecosystem and maintained by Scala developers) so that's not a problem at all.' and @kristofa concurred

We've found it impossible to write pure-java extensions to these projects -- for example we wanted to write a splunk-based span store using the splunk java sdk and could not do it without writing scala.

We (lyft) would prefer the ability to extend the backend components as necessary without having to introduce the scala language / compiler. Simplify providing these components as standalone jars does not allow for this (with the current use of traits as interfaces).

**Comment by b** [comment]
Look like keeping this independent on the Scala traits question was a bit optimistic! My view on that is that it is insufficient and doesn't address what this issue is for.

As @jpinner just described, there is a lot of value in a Java backend, as well. I think if we were to prioritize, elimination of client side Scala needs to come first. I don't think that is sufficient, however. The process of producing Java backend components will be helpful in componentizing things such that the ecosystem can support both Java and Scala backends without making it mutually exclusive.

**Comment by michaelsembwever** [comment]
To come back to this and an attempt to summarise…
- the client-side cleanup takes priority, this is rather obvious. that is done via brave and tickets for further work can exist against it, [client-A], although one might argue it is already done,
- the idea of sharing java interfaces, or having the scala client libraries in this repo built upon the brave interfaces, can be left for another day until the community sees it fit and has momentum there, [client-B]
- the server-side zipkin needs to be java-friendly, to the point that extensions can be written without having to code scala, [server-A]
- the server-side zipkin is to remain at large a scala implementation, with primarily scala written extensions, [!server-B]
- simply replacing scala traits to java interfaces does not solve (server-A),  https://github.com/openzipkin/zipkin/issues/45, that is (server-A2) is the correct approach.

Feel free to jump in and correct this summary.

Based off this i would say that the unresolved issue is, because it sits in the server-side project and it has been confirmed that making the server project more friendly to writing pure java extensions is a need, about (server-A), specifically (server-A2). But beyond that we can and should reassure and clarify to everyone that there will be no big migration of the server over to java, ie (server-B).

Given the length of the discussion in this issue i suggest…
- re-titling this issue as "_Discuss_ eliminating dependency on Scala compiler and runtime" and closing it (given everyone agrees with the summary),
- closing https://github.com/openzipkin/zipkin/issues/451 since it's about (server-A1) which is wrong, 
- open a new issue (in this project) for (server-A2) "Rewrite zipkin-common to java so third-party extensions can be pure java)". While this doesn't do everything we want it's a step in the right direction with well defined limited scope and goal. Hopefully not all of the hurdles and concerns listed in Adrian's comment here https://github.com/openzipkin/zipkin/issues/451#issuecomment-122303113 are relevant if we limit the scope to just zipkin-common?

**Comment by codefromthecrypt** [comment]
I think we should keep this open or move it to a new repo. There are still
many people, myself included, who thing that the Scala implementation is a
large source of drag. This persists regardless of classification systems.
Just reopening yet another issue to say the same thing is tantamount to a
shells game.

**Comment by codefromthecrypt** [comment]
SUMMARY:

This discussion brought to foreground a key issue, which is whether openzipkin/zipkin will allow a pure-java implementation to overtake the existing scala/finagle one. The current scala/finagle one is desired by active contributors including @eirslett and @kristofa 

To allow mutual progress, a pure-server backend should start in its own repository under openzipkin. This repo will focus on allowing JVM backends to be written without a dependency on a specific scala runtime, directly or indirectly. For example, it wouldn't require configuration to be written in scala, nor would accident of thrift serialization end up requiring finagle. It wouldn't focus on ancillary sharing activities, such as attempts to get instrumentation to share the same libraries (like context propagation). It is very important that such a project has a narrow and solvable mission.

I'd expect key stakeholders to be those who've raised their hands before.. at least @b @jpinner @NiteshKant @dsyer @spencergibb. If folks have a good idea for a repo name besides java-zipkin, or if you wish collaborate, raise your hand!

I'll create the repo sometime in the next week and offer to help draft initial libraries.

**Comment by codefromthecrypt** [comment]
ok here it is.. we'll have some issues to discuss before code can be formalized https://github.com/openzipkin/zipkin-java

**Comment by codefromthecrypt** [comment]
Goes without saying, but if at any time openzipkin/zipkin wants to replace components with those in java-zipkin, of course that would be the most ideal outcome.
