### ISSUE TITLE
Cannot show aggregates on Web UI 

### ISSUE THREAD

**Issue by pszymczyk** [openzipkin/zipkin#634]
Hi

I try to display some agregregates from https://github.com/openzipkin/zipkin/blob/master/zipkin-tracegen/src/testdata/aggregates.sql on Web UI and it doesn't work for me, 

Here are steps I made:
- $ vim ./src/main/scala/com/twitter/zipkin/example/Main.scala

```
l22: val genSampleTraces = flag("genSampleTraces", false, "Generate sample traces") >> val genSampleTraces = flag("genSampleTraces", true, "Generate sample traces")
```
- $ vim ../zipkin-anormdb/src/main/scala/com/twitter/zipkin/anormdb/AnormDBSpanStoreFactory.scala

```
l:23 val anormDB = flag("zipkin.storage.anormdb.db", "sqlite-memory", "name The database type") >>  val anormDB = flag("zipkin.storage.anormdb.db", "sqlite-persistent", "name The database type")
```
- $ ../gradlew :zipkin-example:run
- $ sqlite3 ./build/zipkin.db < ../zipkin-tracegen/src/testdata/aggregates.sql

I expect that after this actions some aggregates will be displayed at http://localhost:8080/aggregate but they are not.

**Comment by dhutchis** [comment]
Aggregates are blank for me as well.  I don't know what should appear on the aggregates page, i.e. if I am missing some configuration or if the page is not implemented or something else.  

I'm running Zipkin using the bin/collector, bin/query and bin/web tools.  I can see traces fine on the main query page.

**Comment by eirslett** [comment]
Aggregates is implemented, but in order to use it, you need to run Hadoop with the analysis job. (And it needs to use Cassandra as a backend)
We'll (hopefully) have support for other backends as well!
@adriancole did we remove the "aggregates" stuff from zipkin-query? In that case, it won't be shown.

**Comment by codefromthecrypt** [comment]
The aggregates api still exists in HBase and Anorm. It is partially
re-implemented in cassandra
https://github.com/openzipkin/zipkin/pull/599/files#diff-d45fcb9231702e1188c7c55289a48c30R19

I understand that none of the apis matter as the hadoop job hasn't
been re-implemented, but even if it was, only cassandra would work?
https://github.com/openzipkin/zipkin-aggregate/issues/2

Regardless, this issue is about anorm. It would be nice to know what
an implementation of the hadoop job would need to do (ex. a unit test
in the aggregate project might help explain this). Even better would
be a non-hadoop answer. For example, some explanation somewhere of
what data must exist for the aggregate UI to operate. I suspect many
won't want to run hadoop, but could process the data in another
fashion.

Thoughts?

**Comment by eirslett** [comment]
I think it's possible to run zipkin-aggregate as a fat jar without hadoop, and it will run in single-node mode. (But I'm not sure really, I can't remember)
If we move to Summingbird, we will get streaming processing, and Summingbird has support for in-memory-processing as well. But then we'd have to rewrite the analysis job - and there are some things you cannot do in streaming jobs that you can do in batch jobs.

We should be able to use [cascading-jdbc](https://github.com/Cascading/cascading-jdbc) for the SQL databases, and [cascading-cassandra](https://github.com/ifesdjeen/cascading-cassandra) (not maintained though :cry:) for Cassandra.
Another option is to setup zipkin-collector with MultiSpanStore and implement a SpanStore that writes to HDFS. Then, we can analyse data from HDFS and we won't need the jdbc/cassandra taps.

**Comment by codefromthecrypt** [comment]
It would be best to have dependencies on projects that aren't orphaned
or at risk of being orphaned. Considering the pain of our past, I'd love to 
not have version locking to a specific scala runtime or EOL JRE.

I know that during the workshop, Jason from groupon mentioned their tracing
analysis story would be via Spark. Any insight into why that may or may not
be a good choice for our aggregate functionality? I've not tried this, but
it seems to have an in-memory mode as well.

**Comment by adriancole** [comment]
cleaned up my last comment

**Comment by codefromthecrypt** [comment]
Parking the discussion on how to implement aggregates here #656, unless we find there's a low-hanging fruit means to implement something for anormdb with current infrastructure.

**Comment by codefromthecrypt** [comment]
I'm closing this particular issue as the aggregates UI does work with recent versions. Instructions on loading are in the zipkin-anormdb README
