### ISSUE TITLE
It's not possible anymore to change consistency level of cassandra driver

### ISSUE THREAD

**Issue by fedj** [openzipkin/zipkin#660]
Hi,

When the change from cassie driver to the native datastax one was made, the consistency level setting disappeared. It was really useful to target local dc.

**Comment by michaelsembwever** [comment]
@fedj are you saying that you'd like to use a consistency level of LOCAL_ONE rather than ONE?

(it is still possible, and rather simple, but the approach has changed, to edit consistency level used by in the *-cassandra.scala files updating QueryOptions using `withQueryOptions(..)` before the cluster is built.)

**Comment by fedj** [comment]
@michaelsembwever Yep, basically we tend to use LOCAL_QUORUM and it was possible to change this consistency level by a configuration flag on the command line.
Btw, congrats for the use of the standard cassandra driver.

**Comment by eirslett** [comment]
I think @michaelsembwever supports this now? Feel free to reopen if the problem isn't solved.
