### ISSUE TITLE
Revamp the zipkin data model

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#780]
Revamp of the data model will be summarized here, after discussion in a [google doc](https://docs.google.com/document/d/1ixxEs9TvhiGjJObGbRSPhSna3zHdadoUTQIZ5JKgLzU/edit)

**Comment by yurishkuro** [comment]
@adriancole what does pinpoint do for sequences?  From their description https://github.com/naver/pinpoint/wiki/Technical-Overview-Of-Pinpoint the data model sounds very similar to Zipkin.

**Comment by codefromthecrypt** [comment]
Naver sends a nextSpanId

https://github.com/naver/pinpoint/blob/master/thrift/src/main/thrift/Trace.thrift#L51

I don't think htrace address sequence explicitly (independent of time)

https://github.com/apache/incubator-htrace/blob/master/htrace-hbase/src/main/protobuf/Span.proto#L29

There's more on the topic of sequence here:
https://docs.google.com/document/d/15wUGaoCnd91EEpy5RhdWU4DwsHBYeP0wGtfFjMLYt6A/edit

**Comment by yurishkuro** [comment]
`nextSpanId` in pinpoint is at the Span Event level - aren't those just like zipkin annotations? That model is so denormalized it's hard to judge. But they do have something else that's interesting

```
  30: optional i32 asyncId;
  31: optional i32 nextAsyncId;
  32: optional i16 asyncSequence;
```

**Comment by codefromthecrypt** [comment]
well both of your points are valid. It was a guess that nextSpanId was
escalated to a real type member (as opposed to any given annotation) for
the purpose of sequencing. I might be wrong. the async stuff, however, is
much more clearly about sequence. @Xylus can you verify?

**Comment by yurishkuro** [comment]
what I am not clear on is why sequencing is important. It was brought up in the context of async spans in the document, where sequencing of async siblings (or, more precisely, of their 'beginSpan' events) doesn't strike me as particularly useful. On the other hand, in the sync context, the call/return pairs can be easily serialized by the timestamps because there is no clock skew in the parent span.

**Comment by codefromthecrypt** [comment]
The use case that leads to this is frame-granularity tracing, like every
method call or cherry-picked ones. Without explicit ordering, you may not
be able to reconstruct the call graph exactly how it existed using only
time, particularly as timestamps are really millis *1000 in a lot of
instrumentation. Feel free to challenge this assumption.

**Comment by yurishkuro** [comment]
Fair enough. `span.beginChildSpan()` can internally assign a sequence number, which can be emitted as a predefine span attribute. 

Adrian, could you please create a "Zipkin v.2 Data Model" doc in the Breakouts folder? There are too many open questions here to discuss in a linear chat.

**Comment by codefromthecrypt** [comment]
@yurishkuro good point. Moved to https://docs.google.com/document/d/1ixxEs9TvhiGjJObGbRSPhSna3zHdadoUTQIZ5JKgLzU/edit

**Comment by Xylus** [comment]
@adriancole @yurishkuro 
`nextSpanId`, and `async*` variables do similar stuff but are used in different circumstances in Pinpoint.

**nextSpanId**
We use both `nextSpanId` of the parent, and `parentSpanId` of the child to reconstruct the call graph. Do note that this was done to support in-process traces (is this frame-granularity trace?). For example:

```
* Note that "Span" in our case denotes a single node, "SpanEvent" denotes a method-level trace
----> | Span (id=1)
      | SpanEvent seq=0 (nextSpanId=11) -----> | Span (id=11, parentSpanId=1)
      | SpanEvent seq=1
      | SpanEvent seq=2 (nextSpanId=12) ----------> | Span (id=12, parentSpanId=1)
* Also Note that only RPC SpanEvents have nextSpanIds.
```

Without `nextSpanId`, we couldn't map Spans 11 and 12 to a SpanEvent and by extension give them ordering (as SpanEvents have sequences within them). `nextSpanId` is issued by the parent and the child uses it as it's Span id.
Plus, using both `nextSpanId` and `parentSpanId` to reconstruct the call graph helps in mitigating SpanId collision (two-way comparison.instead of one).

**async\* variables**
Similar to `nextSpanId` above, but used for context propagation across threads. We emulate an asynchronous call as a new Span internally (except we don't create a new node for it), kinda similar to the example above but with asynchronous invocations instead of RPC calls. For example,

```
----> Span (id=1)
      | SpanEvent seq=0
      | SpanEvent seq=1 (nextAsyncId=11) ----async----> | Async "Span" (id=11)
      | SpanEvent seq=2
```

This is exactly the same as what happens in RPC calls, except that a SpanEvent may have more than 1 asynchronous invocations :

```
----> Span (id=1)
      | SpanEvent seq=0
      | SpanEvent seq=1 (nextAsyncId=11) ----async----> | Async "Span" asyncSequence=0 (id=11)
      |                                  |---async----> | Async "Span" asyncSequence=1 (id=11)
      | SpanEvent seq=2
```

Hope I got everything right without confusing everyone too much.

PS. wanted to post something on this to the Google Docs, but didn't know how to edit it nicely :)

**Comment by michaelsembwever** [comment]
> particularly as timestamps are really millis *1000 in a lot of instrumentation

is it still needed if this is fixed. clients/platforms that do a lot of frame-granularity are going to want real microsecond instrumentation.

> …  in the Breakouts folder?

where's this folder?

**Comment by yurishkuro** [comment]
@michaelsembwever https://drive.google.com/folderview?id=0B0tSnQT3uGdAfmZaVzZfOXJRRzZPUmRDRFVGRUFHVm1fX2ZXenM1VGN3RElTQzc3azI3X1k&usp=sharing&tid=0B0tSnQT3uGdAfndwS3RKVnMtM0ZKMWU4R1dicTNEXy1NSlBJaTlJQ05abGVneTlucW5HdFk#list

**Comment by codefromthecrypt** [comment]
@Xylus great detail. I think I understood this completely?!

@michaelsembwever in brave, finagle, etc, how do you think we can get to micros precision? Do share your tricks!

**Comment by michaelsembwever** [comment]
@adriancole you can use the microseconds component from System.nanoTime().

That microseconds within milliseconds arn't in sync between machines isn't of any great concern. 

You might want to skew it by a fixed amount so the the microseconds component ticks over to zero when System.currentTimeMillis() goes to the next millsecond value.

**Comment by jorgheymans** [comment]
This seems to be referring to zipkin v2 data model which has been released.
