### ISSUE TITLE
[1.25.1] too many tombstones in zipkin.span_duration_index

### ISSUE THREAD

**Issue by lycplus** [openzipkin/zipkin#872]
Currently, we encounter this error in our cassandra:

```
ERROR 03:24:53 Scanned over 100000 tombstones in zipkin.span_duration_index; query aborted (see tombstone_failure_threshold)
ERROR 03:24:53 Scanned over 100000 tombstones in zipkin.span_duration_index; query aborted (see tombstone_failure_threshold)
ERROR 03:24:53 Scanned over 100000 tombstones in zipkin.span_duration_index; query aborted (see tombstone_failure_threshold)
WARN  03:24:53 Uncaught exception on thread Thread[SharedPool-Worker-59,5,main]: {}
java.lang.RuntimeException: org.apache.cassandra.db.filter.TombstoneOverwhelmingException
```

Is this because of updating of schema? what usage can cause this error?

**Comment by ccl0326** [comment]
Can anyone have a look it?Any optimize solution?Thx.

**Comment by codefromthecrypt** [comment]
@michaelsembwever @yurishkuro any thoughts?

**Comment by yurishkuro** [comment]
beats me. The primary key has both a timestamp and a trace ID

```
PRIMARY KEY ((service_name, span_name, bucket), duration, ts, trace_id)
```

Since we index each span individually, perhaps we can add a span ID as well?

**Comment by michaelsembwever** [comment]
(still not getting github notifications, quite frustrating)

@yurishkuro (i do believe) you can avoid this problem by `startTs = max(startTs,  TimeUnit.MILLISECONDS.toMicros(System.currentTimeMillis()) - TimeUnit.SECONDS.toMicros(ttl));` in Repository.getTraceIdsByDuration(..)

That is you can avoid queries going into those buckets that we already know are only going to be filled with tombstones.

**Comment by yurishkuro** [comment]
@michaelsembwever not sure I follow. The table's TTL should simply expire the records after N days and drop them during compactions. But they shouldn't create tombstones any more than with any other table in zipkin schema. Where I do see tombstones being possible is if the spans are sub-millisecond, i.e. true microseconds timestamps are different, but they are reported from a millisecond-precision language like JS, thus producing non-unique PKs.

Is there a way in C\* to read tombstoned data and compare it with live keys, to understand what exactly is different between the two and what causes the PKs to be overwritten?

**Comment by michaelsembwever** [comment]
@yurishkuro  In this situation we're talking about expired cells, rather than tombstones from explicit deletes. But it's the same thing, and they exist up until the compaction hits them.

So in the situation where compactions have not yet run (or where compactions are constantly executing and the "tombstone compaction" never gets to execute) then these queries will try to read from buckets that are filled with expired cells, resulting in the error message reported above.

> But they shouldn't create tombstones any more than with any other table in zipkin schema.

Correct. But the other tables don't have read patterns against them that will hit rows with so many tombstones. 

We know that Cassandra won't return cells that are expired, ie older than the TTL, so why include them in the query?

**Comment by yurishkuro** [comment]
> In this situation we're talking about expired cells, rather than tombstones from explicit deletes.

Not sure how C\* does this, does it treat cells past TTL as tombstones as well?

We already filter by startTs:

```
                            return StreamSupport
                                    .stream(it.spliterator(), false)
                                    .map(DurationRow::new)
                                    .filter((row) -> row.timestamp >= startTs && row.timestamp <= endTs)
                                    .limit(limit)
                                    .collect(Collectors.toList());
```

However, I am not sure it helps in this case since the `ts` column comes after the `duration`.

It could also be that @liyichao has his installation misconfigured where the lookback period is longer than TTL.

If it's the case that we're running into expired records, maybe @liyichao needs to tweak the settings to make sure expiration compactions are done reliably? What's `gc_grace_seconds` set to?  We have it set to 0, since zipkin schema doesn't do any updates.

**Comment by michaelsembwever** [comment]
> Not sure how C\* does this, does it treat cells past TTL as tombstones as well?

Short answer is yes :-)

> We already filter by startTs: …

This is too late. We want to prevent asking for data that won't ever be returned but still will cause Cassandra to churn and throw the error. 

> If it's the case that we're running into expired records, maybe @liyichao needs to tweak the settings to make sure expiration compactions are done reliably?

Having a datamodel and read pattern that's going to have to read and filter out so many TTL'd values is a known anti-pattern in Cassandra. It really is upon us to fix that.

**Comment by yurishkuro** [comment]
We have a dual filter in this query, d1 <= duration <= d2 and t1 <= timestamp <= t2, something that Cassandra cannot handle without client-side joins. The partition key `(service_name, span_name, bucket)` includes the time bucket, which is a timestamp floored to a certain precision (1hr by default). If the installation is configured with TTL > default lookback, the query should never look at expired cells. The client-side filter on the timestamp is actually no-op in most cases, except for the edge buckets. Sure, we can put a `min(ttl, lookback)` when calculating the startTs, which of course only helps if your ttl in the query service matches the actual TTL in the DB.

**Comment by michaelsembwever** [comment]
>  If the installation is configured with TTL > default lookback, the query should never look at expired cells.

This aspect is a little unknown to me. But i'll put forth a patch and see what you think.

**Comment by michaelsembwever** [comment]
closing. see PR.
