### ISSUE TITLE
Track indirect service dependencies

### ISSUE THREAD

**Issue by yurishkuro** [openzipkin/zipkin#923]
Imagine a case where some routing layer like haproxy is adding its own spans to passing-through traces. This makes the dependency graph not very interesting, as instead of `a->b` links, for any  pair of `a` and `b`, we would get `a->haproxy` and `haproxy->b`. Such edges have merit, but they completely lose the `a->b` dependency, even though the data in the spans has it.

We can extend the dependencies data structure to still allow links `a->b` to be present, but marked as "indirect". The UI can be extended to toggle between showing/hiding indirect links.

Or maybe there's even better way, open to suggestion. For example, when you mouse-over a service in the diagram, it dims unconnected services and highlights directly connected ones. For service A above it would highlighght `haproxy`, but dim B. It would be nice in that mode to also show 2-hops services, e.g. highlight B as well, but in different color.

**Comment by codefromthecrypt** [comment]
interesting idea.. I think you mentioned something along these lines in the
past.

How are you thinking this is signaled? We are assuming that the proxies are
creating core annotations and/or server address ones I guess, else they'd
not show up anyway. Would this be a field or attribute on the span ex. the
 SpanKind type of deal? or a well-known tag/binary annotation?

Or would the result be specified (ex. indirect attribute on a link), but
how that's populated left to the dependency link parser/job?

**Comment by yurishkuro** [comment]
Oh, I wasn't thinking of some "magical" services here (it's a different issue), but of a normal service that creates normal spans as any other service. But from the system architecture view this service X looks like a proxy of sort, e.g. it can have 50 services on the left and 200 services on the right, and the only path from left to right is through X. So the diagram looks like {50}->X->{200}, but gives no indication of the actual dependencies between left and right side. Maybe one of 50 depends only on one of 200, we can't tell from the diagram. But the trace data does tell that, so I'd like to have a way to reflect it in the diagram.

Note that this problem has a second level of depth - showing dependencies by span/operation name, which is also something my users are very interested in. It would be nice to come up with a richer aggregation data model than just (parent, child, count), so that it would allow answering these questions.

**Comment by eirslett** [comment]
One of the problems with the dependencies view today is that it assumes a directed asyclic graph, while introducing haproxy into the mix would create circular dependencies, like in "a -> haproxy -> b -> haproxy -> c".
It assumes a DAG because... nobody would ever introduce cyclic dependencies between microservices... right...?

**Comment by virtuald** [comment]
As a new user, I'm adding zipkin to my system because I _don't_ know what my system is doing underneath the hood. Chances are, because the system architecture isn't managed at all (complex political problem...), it's not a DAG.

**Comment by eirslett** [comment]
There are also a couple of other "valid" cases for not having a DAG, for example, at FINN.no we have something like this:

varnish -> finn.no -> varnish -> api -> database

The underlying Spark job doesn't assume a DAG, that's only our UI. So we could rewrite it with another JavaScript library than dagre/d3, but it would take some work. (PRs welcome, I suppose?)

**Comment by yurishkuro** [comment]
The discussion is etching away from original topic, but afaik there is no restriction on the architecture diagram to be a DAG, e.g. below there are bidirectional dependencies. 
![image](https://cloud.githubusercontent.com/assets/3523016/15193145/6c9d26be-178a-11e6-88ef-6a3fd98bd3cb.png)

**Comment by eirslett** [comment]
It does happen sometimes, I'm not sure why. Dagre is DAG-specific: https://github.com/cpettitt/dagre
Maybe the behavior is undetermined when you provide a cyclic graph...

Anyways, the UI won't break entirely if you have cycles! It's just that the rendering library is originally meant for DAGs.

**Comment by jakerobb** [comment]
A year later, I'm wondering if you came to a solution here.

Seems to me that if you have a->haproxy->b, you could instrument haproxy differently. For example,  it could set specialized annotations on the a->b span instead of the standard cs/sr/ss/cr on its own span? Perhaps it could set proxy-receive and proxy-send? I think that would be sufficient to prevent the dependency graph from collapsing down as you've described.

**Comment by codefromthecrypt** [comment]
>
> A year later, I'm wondering if you came to a solution here.
>
solutions usually aren't a function of time, rather hands available and
interest. Ex. elasticsearch hung around until it was implemented w/in a
couple weeks. Features need a champion as otherwise they don't get done.

> Seems to me that if you have a->haproxy->b, you could instrument haproxy
> differently. For example, it could set specialized annotations on the a->b
> span instead of the standard cs/sr/ss/cr on its own span? Perhaps it could
> set proxy-receive and proxy-send? I think that would be sufficient to
> prevent the dependency graph from collapsing down as you've described.
>
Firstly, I'm not sure if there is instrumentation for haproxy ... if there
is, please tell! One approach is for proxies to be pass-through (though
that's really lack of approach) One of the more recent proxy-like things
zipkinized is envoy which uses standard annotations. I think we have to
assume that intermediaries will be instrumented, and changing their
instrumentation to fit the graph wouldn't help.

OTOH, we could consider a code option. By the time the data gets to the UI
or the api, it is too late I think. However, a dependency link job could
creating skip links based on a pattern like a service name. This wouldn't
be much code, and it doesn't require more data that is already pulled.

**Comment by jorgheymans** [comment]
3.5 years later, and nobody stepped up to carry the idea forward or voice interest in it. I'm going to close this, feel free to reopen if you think there is still some merit in the idea or it's worth reviving it for some reason.
