### ISSUE TITLE
CorrectForClockSkew shouldn't adjust explicitly set Span.duration

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#955]
`CorrectForClockSkew` currently changes span duration even if it was set by instrumentation. This is a problem.

In order to not meddle with explicitly set duration, we may have to change behavior a bit. Most collectors invoke `ApplyTimestampAndDuration` _before_ storing the spans. `CorrectForClockSkew` is applied at query time, and so can't tell if Span.duration was set by instrumentation, or by `ApplyTimestampAndDuration`! The thing is.. we need duration to be set in order for duration query to work!

One way to unwind this is to not assign missing duration at ingest. Rather, only do this at query time. Note: this would limit duration query support to recently maintained tracers, as old ones don't set Span.duration.

**Comment by codefromthecrypt** [comment]
@yurishkuro do you have an opinion on this?

**Comment by yurishkuro** [comment]
tbh, I don't even know when it's valid for a child to affect parent's duration, which is what causes updates to duration in the adjuster. If a client emitted cs/cr, their difference defines the duration and no clock skew should be able to affect it. If the server logged a pair of sr/ss, then their difference should never be larger than the client side duration, independent of clock skew, as otherwise it breaks causality. The only scenario where server span can be longer than client span is in fire and forget cases, which arguably should not be modeled with client and server sharing the span ID.

So unless I am missing a use case, it seems perfectly valid for collectors to precompute duration based on annotations (ideally from the same host), and clock skew adjuster should never need to change that duration.

**Comment by codefromthecrypt** [comment]
I have a similar opinion. will change the clock skewer to never adjust
span.duration
