### ISSUE TITLE
[ui] Spans are shifted to the left (their relative time is negative)

### ISSUE THREAD

**Issue by marcingrzejszczak** [openzipkin/zipkin#968]
Image:
![spans_bug](https://cloud.githubusercontent.com/assets/3297437/13008274/a5d52c78-d195-11e5-951d-43e077bff57a.png)

JSON:
[spans_bug.txt](https://github.com/openzipkin/zipkin/files/128042/spans_bug.txt)

**Comment by codefromthecrypt** [comment]
Is the attached json the input or output? Ex is this what was posted to the
zipkin server or what was returned by the query? Reason I ask is that the
query response includes clock skew adjustment.

**Comment by marcingrzejszczak** [comment]
This is what was returned from the query server

**Comment by codefromthecrypt** [comment]
Couple things can help make it easier for people to pick up the sort of
issues you are raising (me or otherwise).

You'll notice Yuri, Yuki and I usually write a failing test or otherwise.
It usually isn't a UI issue, rather a data one.

I guess you believe this is a JavaScript problem or something in the
mustache code, as you tagged this as a UI bug.

Can annotate the image with an arrow or something pointing to where you
think something can be.  Please also pare down test data to only a few
spans, and mention specifically the span data (ex timestamp on which span)
you think the UI is misunderstanding.

That makes issues like these easier to validate. If this isn't a UI issue
(rather something around the api, it might need to go to another repo.

The more you can clarify, the easier it is for others to help you.

**Comment by codefromthecrypt** [comment]
When clock skew is present, a child comes before the parent. This isn't something the UI should do anything about, as root cause is preventable. Basically, instead we should correct the instrumentation.

I hunted through the attached trace, it looks like RPC methods like http client or server calls do not log any core annotations. This means clock skew correction will not work. Since the spans that shifted are in fact RPC spans, the simplest way to correct this issue is to log RPC annotations.

spring-cloud-sleuth used to do this, at least some of the code still does (ex `ZipkinSpanListener`).

I cc'd you on this topic the day before you opened this :P #963

Also, of interest is #939 which I opened a couple weeks ago, but no-one has given feedback on.

**Comment by codefromthecrypt** [comment]
ps probably also want to fix your json formatter to not coerse longs to floating points.

ex. formatting like this, while valid json, is unnecessarily confusing way to read an epoch timestamp.

``` json
    "timestamp": 1.455283179037e+15,
```
